import { PrismaClient, Contact, Vehicle, MarketingCampaign } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding MAALAL CARS database with realistic Moroccan automotive data...')

  // 1. Roles & Permissions
  const superAdminRole = await prisma.role.upsert({
    where: { name: 'Super Admin' },
    update: {},
    create: {
      name: 'Super Admin',
      description: 'Super Administrateur avec pouvoirs exclusifs de validation finale des ventes et restauration des archives',
    },
  })

  const _adminRole = await prisma.role.upsert({
    where: { name: 'Administrateur' },
    update: {},
    create: {
      name: 'Administrateur',
      description: 'Accès complet à toutes les fonctionnalités et paramètres système',
    },
  })

  const managerRole = await prisma.role.upsert({
    where: { name: 'Gestionnaire' },
    update: {},
    create: {
      name: 'Gestionnaire',
      description: 'Gestion des opérations quotidiennes, stock, ventes, clients et achats',
    },
  })

  const commercialRole = await prisma.role.upsert({
    where: { name: 'Vendeur' },
    update: {},
    create: {
      name: 'Vendeur',
      description: 'Gestion des opportunités, réservations, ventes et contacts clients',
    },
  })

  const accountantRole = await prisma.role.upsert({
    where: { name: 'Comptable' },
    update: {},
    create: {
      name: 'Comptable',
      description: 'Gestion financière, factures, encaissements, décaissements et TVA',
    },
  })

  const assistantRole = await prisma.role.upsert({
    where: { name: 'Assistante' },
    update: {},
    create: {
      name: 'Assistante',
      description: 'Support administratif, cartes grises, dossiers et accueil',
    },
  })

  // 2. Users
  const passwordHash = await bcrypt.hash('password123', 10)
  const maalalPasswordHash = await bcrypt.hash('Maalal@x1', 10)

  const adminUser = await prisma.user.upsert({
    where: { email: 'maalalcars.911@gmail.com' },
    update: { roleId: superAdminRole.id },
    create: {
      email: 'maalalcars.911@gmail.com',
      name: 'Maalal Admin',
      phone: '+212 6 00 00 00 00',
      passwordHash: maalalPasswordHash,
      roleId: superAdminRole.id,
      isActive: true,
    },
  })

  await prisma.user.upsert({
    where: { email: 'sarah.martin@maalalcars.com' },
    update: {},
    create: {
      email: 'sarah.martin@maalalcars.com',
      name: 'Sarah Martin',
      phone: '+212 6 62 34 56 78',
      passwordHash,
      roleId: managerRole.id,
      isActive: true,
    },
  })

  const yassineUser = await prisma.user.upsert({
    where: { email: 'yassine.benali@maalalcars.com' },
    update: {},
    create: {
      email: 'yassine.benali@maalalcars.com',
      name: 'Yassine Benali',
      phone: '+212 6 63 45 67 89',
      passwordHash,
      roleId: commercialRole.id,
      isActive: true,
    },
  })

  const karimUser = await prisma.user.upsert({
    where: { email: 'karim.lahbili@maalalcars.com' },
    update: {},
    create: {
      email: 'karim.lahbili@maalalcars.com',
      name: 'Karim Lahbili',
      phone: '+212 6 64 56 78 90',
      passwordHash,
      roleId: accountantRole.id,
      isActive: true,
    },
  })

  await prisma.user.upsert({
    where: { email: 'nadia.zahra@maalalcars.com' },
    update: {},
    create: {
      email: 'nadia.zahra@maalalcars.com',
      name: 'Nadia Zahra',
      phone: '+212 6 65 67 89 01',
      passwordHash,
      roleId: assistantRole.id,
      isActive: true,
    },
  })

  const salmaUser = await prisma.user.upsert({
    where: { email: 'salma.mansouri@maalalcars.com' },
    update: {},
    create: {
      email: 'salma.mansouri@maalalcars.com',
      name: 'Salma Mansouri',
      phone: '+212 6 67 89 01 23',
      passwordHash,
      roleId: commercialRole.id,
      isActive: true,
    },
  })

  // 3. Application Settings & Company Profile
  const defaultSettings = [
    { key: 'company_name', value: 'MAALAL CARS SARL', category: 'company', description: 'Raison sociale légale' },
    { key: 'company_ice', value: '001234567890023', category: 'company', description: 'Identifiant Commun de l’Entreprise (ICE)' },
    { key: 'company_rc', value: '123456', category: 'company', description: 'Registre du Commerce (Casablanca)' },
    { key: 'company_if', value: '58789012', category: 'company', description: 'Identifiant Fiscal (IF)' },
    { key: 'company_patente', value: '34567890', category: 'company', description: 'Numéro de Patente' },
    { key: 'company_address', value: 'Lot 123, Zone Industrielle Sidi Maarouf, 20150 Casablanca, Maroc', category: 'company', description: 'Adresse du siège social' },
    { key: 'company_phone', value: '+212 5 22 12 34 56', category: 'company', description: 'Téléphone principal' },
    { key: 'company_email', value: 'contact@maalalcars.ma', category: 'company', description: 'Email de contact' },
    { key: 'company_website', value: 'www.maalalcars.ma', category: 'company', description: 'Site web' },
    { key: 'currency', value: 'MAD', category: 'general', description: 'Devise principale' },
    { key: 'currency_display', value: 'DH', category: 'general', description: 'Symbole affiché' },
    { key: 'locale', value: 'fr-MA', category: 'general', description: 'Paramètres régionaux' },
    { key: 'timezone', value: 'Africa/Casablanca', category: 'general', description: 'Fuseau horaire' },
    { key: 'invoice_prefix', value: 'FAC', category: 'invoice', description: 'Préfixe de facturation' },
    { key: 'invoice_counter', value: '50', category: 'invoice', description: 'Compteur courant de facturation' },
    { key: 'invoice_terms', value: 'Paiement sous 30 jours par virement ou chèque bancaire au Maroc.', category: 'invoice', description: 'Conditions de règlement' },
    { key: 'invoice_footer', value: 'MAALAL CARS SARL - Capital de 2 000 000 DH - RC 123456 Casablanca - ICE 001234567890023', category: 'invoice', description: 'Pied de page des documents légaux' },
  ]

  for (const s of defaultSettings) {
    await prisma.applicationSetting.upsert({
      where: { key: s.key },
      update: { value: s.value, description: s.description, category: s.category },
      create: s,
    })
  }

  // 4. Vehicle Brands & Models
  const brandsData = [
    {
      name: 'Toyota',
      country: 'Japon',
      models: ['Land Cruiser', 'RAV4', 'Corolla', 'Hilux', 'Yaris', 'Prado'],
    },
    {
      name: 'BMW',
      country: 'Allemagne',
      models: ['X5', 'X3', 'Série 3', 'Série 5', 'M4', 'X6', 'Série 1'],
    },
    {
      name: 'Mercedes-Benz',
      country: 'Allemagne',
      models: ['GLC', 'C-Class', 'E-Class', 'GLE', 'A-Class', 'CLA', 'G-Class'],
    },
    {
      name: 'Audi',
      country: 'Allemagne',
      models: ['Q7', 'A4', 'A6', 'Q5', 'Q3', 'Q8', 'A3'],
    },
    {
      name: 'Land Rover',
      country: 'Royaume-Uni',
      models: ['Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Defender'],
    },
    {
      name: 'Hyundai',
      country: 'Corée du Sud',
      models: ['Tucson', 'Santa Fe', 'Creta', 'Elantra', 'i20'],
    },
    {
      name: 'Peugeot',
      country: 'France',
      models: ['3008', '208', '2008', '508', 'Partner', 'Rifter'],
    },
    {
      name: 'Renault',
      country: 'France',
      models: ['Clio', 'Megane', 'Captur', 'Kadjar', 'Express'],
    },
    {
      name: 'Dacia',
      country: 'Roumanie',
      models: ['Duster', 'Sandero Stepway', 'Logan', 'Dokker'],
    },
    {
      name: 'Porsche',
      country: 'Allemagne',
      models: ['Macan', 'Cayenne', 'Panamera', '911'],
    },
  ]

  for (const b of brandsData) {
    const brand = await prisma.vehicleBrand.upsert({
      where: { name: b.name },
      update: {},
      create: { name: b.name, country: b.country },
    })

    for (const m of b.models) {
      await prisma.vehicleModel.upsert({
        where: {
          brandId_name: {
            brandId: brand.id,
            name: m,
          },
        },
        update: {},
        create: {
          name: m,
          brandId: brand.id,
          bodyType: m.includes('X') || m.includes('Q') || m.includes('GL') || m.includes('Land') || m.includes('Range') || m.includes('Tucson') || m.includes('3008') || m.includes('Duster') || m.includes('Macan') || m.includes('Cayenne') ? 'SUV' : 'Berline',
        },
      })
    }
  }

  // 5. Expense Categories
  const expenseCategories = [
    { name: 'Transport & Rapatriement', code: 'TRANSP', defaultTax: 20.0, description: 'Frais de transport dépanneuse et transit' },
    { name: 'Préparation Esthétique & Detailing', code: 'PREP', defaultTax: 20.0, description: 'Lavage, lustrage, céramique, nettoyage intérieur' },
    { name: 'Atelier & Mécanique', code: 'MECA', defaultTax: 20.0, description: 'Réparations, vidanges, filtres, pièces d’usure' },
    { name: 'Carrosserie & Peinture', code: 'CARRO', defaultTax: 20.0, description: 'Tôlerie, retouches peinture, débosselage' },
    { name: 'Carburant', code: 'CARB', defaultTax: 20.0, description: 'Plein carburant pour livraison et essais' },
    { name: 'Administratif & Carte Grise', code: 'ADMIN', defaultTax: 0.0, description: 'Frais de mutation, timbres, légalisations' },
    { name: 'Assurance Flotte & Transit', code: 'ASSUR', defaultTax: 10.0, description: 'Polices temporaires et garanties' },
    { name: 'Commission Intermédiaire', code: 'COMM', defaultTax: 0.0, description: 'Commission versée aux semsars et courtiers' },
    { name: 'Marketing & Publicité', code: 'PUB', defaultTax: 20.0, description: 'Shooting photo pro, annonces sponsorisées' },
    { name: 'Contrôle Technique', code: 'CT', defaultTax: 20.0, description: 'Visite technique et contrôle pollution' },
  ]

  for (const ec of expenseCategories) {
    await prisma.expenseCategory.upsert({
      where: { code: ec.code },
      update: { name: ec.name, defaultTax: ec.defaultTax, description: ec.description },
      create: ec,
    })
  }

  // 6. Contacts CRM (Acheteurs, Vendeurs, Commissionnaires, Fournisseurs, Clients)
  const contactsData = [
    // Acheteurs / Clients
    {
      code: 'CLT-001',
      type: 'INDIVIDUAL',
      role: 'BUYER',
      firstName: 'Imane',
      lastName: 'Zahiri',
      email: 'imane.zahiri@gmail.com',
      phone: '+212 6 12 34 56 78',
      cin: 'BE123456',
      city: 'Casablanca',
      address: 'Résidence Les Roses, Boulevard Ghandi',
      segment: 'VIP',
      rating: 4.9,
      totalVolume: 1248500,
      currentDebt: 24900,
      notes: 'Cliente fidèle, achète régulièrement pour sa flotte et sa famille.',
    },
    {
      code: 'CLT-002',
      type: 'INDIVIDUAL',
      role: 'BUYER',
      firstName: 'Youssef',
      lastName: 'El Idrissi',
      email: 'youssef.elidrissi@gmail.com',
      phone: '+212 6 23 45 67 89',
      cin: 'A456789',
      city: 'Rabat',
      address: 'Avenue Mohammed VI, Souissi',
      segment: 'PROSPECT_CHAUD',
      rating: 4.8,
      totalVolume: 980400,
      currentDebt: 0,
      notes: 'Chef d’entreprise, apprécie les SUV allemands récents.',
    },
    {
      code: 'CLT-003',
      type: 'INDIVIDUAL',
      role: 'BUYER',
      firstName: 'Karim',
      lastName: 'Bennani',
      email: 'karim.bennani@gmail.com',
      phone: '+212 6 34 56 78 90',
      cin: 'K789012',
      city: 'Tanger',
      address: 'Malabata, Tanger',
      segment: 'FIDELE',
      rating: 4.7,
      totalVolume: 856200,
      currentDebt: 12600,
      notes: 'Paiements réguliers par virement bancaire.',
    },
    {
      code: 'CLT-004',
      type: 'INDIVIDUAL',
      role: 'BUYER',
      firstName: 'Omar',
      lastName: 'Bennis',
      email: 'omar.bennis@gmail.com',
      phone: '+212 6 45 67 89 01',
      cin: 'C345678',
      city: 'Fès',
      address: 'Route d’Imouzzer, Fès',
      segment: 'FIDELE',
      rating: 4.9,
      totalVolume: 745600,
      currentDebt: 26200,
      notes: 'Achat de 4 véhicules au cours des 2 dernières années.',
    },
    {
      code: 'CLT-005',
      type: 'COMPANY',
      role: 'BUYER',
      companyName: 'AutoFleet Services SARL',
      ice: '002983746000012',
      rc: '98452 Casablanca',
      email: 'contact@autofleet.ma',
      phone: '+212 5 22 45 67 89',
      city: 'Casablanca',
      address: 'Technopark, Route de Nouaceur',
      segment: 'VIP',
      rating: 5.0,
      totalVolume: 2450000,
      currentDebt: 45000,
      notes: 'Compte entreprise de location longue durée.',
    },
    // Vendeurs Particuliers & Pros
    {
      code: 'VEN-001',
      type: 'INDIVIDUAL',
      role: 'SELLER',
      firstName: 'Said',
      lastName: 'El Alami',
      email: 'said.alami@gmail.com',
      phone: '+212 6 56 78 90 12',
      cin: 'BK654321',
      city: 'Casablanca',
      address: 'Ain Diab, Casablanca',
      segment: 'STANDARD',
      rating: 4.8,
      totalVolume: 598400,
      currentDebt: 0,
      notes: 'Fournisseur régulier de berlines de luxe en première main.',
    },
    {
      code: 'VEN-002',
      type: 'INDIVIDUAL',
      role: 'SELLER',
      firstName: 'Hicham',
      lastName: 'El Khayat',
      email: 'hicham.khayat@gmail.com',
      phone: '+212 6 67 89 01 23',
      cin: 'D987654',
      city: 'Meknès',
      address: 'Quartier Hamria, Meknès',
      segment: 'STANDARD',
      rating: 4.6,
      totalVolume: 487200,
      currentDebt: 0,
      notes: 'Vendeur de véhicules récents très bien entretenus.',
    },
    // Commissionnaires (Courtiers / Semsars)
    {
      code: 'COM-001',
      type: 'INDIVIDUAL',
      role: 'COMMISSIONER',
      firstName: 'Yassine',
      lastName: 'Benali',
      email: 'yassine.courtier@gmail.com',
      phone: '+212 6 61 23 45 67',
      cin: 'BE987654',
      city: 'Casablanca',
      address: 'Maârif, Casablanca',
      segment: 'VIP',
      rating: 4.9,
      totalVolume: 5845000,
      currentDebt: 12450,
      notes: 'Meilleur apporteur d’affaires sur la région de Casablanca.',
    },
    {
      code: 'COM-002',
      type: 'INDIVIDUAL',
      role: 'COMMISSIONER',
      firstName: 'Karim',
      lastName: 'Laalou',
      email: 'karim.laalou@gmail.com',
      phone: '+212 6 34 56 78 90',
      cin: 'R123456',
      city: 'Rabat',
      address: 'Agdal, Rabat',
      segment: 'VIP',
      rating: 4.8,
      totalVolume: 4680000,
      currentDebt: 18200,
      notes: 'Réseau influent auprès des hauts cadres et corps diplomatique.',
    },
    {
      code: 'COM-003',
      type: 'INDIVIDUAL',
      role: 'COMMISSIONER',
      firstName: 'Samira',
      lastName: 'El Amrani',
      email: 'samira.amrani@gmail.com',
      phone: '+212 6 78 90 12 34',
      cin: 'M456789',
      city: 'Marrakech',
      address: 'Guéliz, Marrakech',
      segment: 'FIDELE',
      rating: 4.7,
      totalVolume: 3920000,
      currentDebt: 9500,
      notes: 'Spécialisée sur la clientèle des maisons d’hôtes et expatriés.',
    },
    // Fournisseurs de Services & Pièces
    {
      code: 'FOUR-001',
      type: 'COMPANY',
      role: 'SUPPLIER',
      companyName: 'Bosch Automotive Maroc',
      ice: '001567894000045',
      rc: '67890 Casablanca',
      email: 'contact@bosch-auto.ma',
      phone: '+212 5 22 89 01 23',
      city: 'Casablanca',
      address: 'Zone Industrielle Ain Sebaa, Casablanca',
      segment: 'FOURNISSEUR',
      rating: 4.9,
      totalVolume: 198450,
      currentDebt: 12450,
      notes: 'Fournisseur officiel de pièces électroniques, filtres et freinage.',
    },
    {
      code: 'FOUR-002',
      type: 'COMPANY',
      role: 'SUPPLIER',
      companyName: 'Auto Clean Pro Detailing',
      ice: '002345678000089',
      rc: '112233 Casablanca',
      email: 'contact@autocleanpro.ma',
      phone: '+212 6 62 11 22 33',
      city: 'Casablanca',
      address: 'Boulevard Yaacoub El Mansour, Casablanca',
      segment: 'FOURNISSEUR',
      rating: 4.8,
      totalVolume: 45600,
      currentDebt: 3200,
      notes: 'Partenaire de lavage intégral, polissage et traitement céramique.',
    },
    {
      code: 'FOUR-003',
      type: 'COMPANY',
      role: 'SUPPLIER',
      companyName: 'TotalEnergies Lubrifiants Maroc',
      ice: '000123456000078',
      rc: '4567 Casablanca',
      email: 'service.client@totalenergies.ma',
      phone: '+212 5 22 78 90 12',
      city: 'Casablanca',
      address: 'Boulevard Moulay Ismail, Casablanca',
      segment: 'FOURNISSEUR',
      rating: 4.9,
      totalVolume: 89400,
      currentDebt: 0,
      notes: 'Fournisseur huiles moteur Quartz, liquide de refroidissement et fluides.',
    },
  ]

  const createdContacts: Record<string, Contact> = {}
  for (const c of contactsData) {
    const contact = await prisma.contact.upsert({
      where: { code: c.code },
      update: c,
      create: c,
    })
    createdContacts[c.code] = contact
  }

  // 7. Véhicules en Stock, Réservés, Vendus, et Vieillissement
  const now = new Date()
  const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000)

  const vehiclesData = [
    // 0 - 30 jours (Stock récent)
    {
      code: 'V-2026-0001',
      vin: 'JTMHV02J404567890',
      matricule: '12345 | A | 6',
      brand: 'Toyota',
      model: 'Land Cruiser',
      version: 'VXR 4.0L V6 Essence Auto',
      bodyType: 'SUV',
      year: 2023,
      colorExterior: 'Blanc Nacré',
      colorInterior: 'Cuir Beige',
      fuelType: 'ESSENCE',
      transmission: 'AUTOMATIQUE',
      mileage: 12450,
      doors: 5,
      seats: 7,
      fiscalPower: 17,
      location: 'Casablanca Showroom',
      entryDate: daysAgo(12),
      purchasePrice: 650000,
      targetSalePrice: 785000,
      minSalePrice: 750000,
      actualSalePrice: 780000,
      status: 'IN_STOCK',
      options: JSON.stringify(['Toit ouvrant', 'Caméra 360°', 'Cuir', 'JBL Premium Sound', 'Climatisation auto quadrizone', 'Navigation', 'Sièges chauffants/ventilés']),
      description: 'Toyota Land Cruiser VXR modèle 2023 en état neuf, première main, carnet complet d’entretien chez Toyota Maroc.',
    },
    {
      code: 'V-2026-0002',
      vin: 'WBAJU710X0GX00123',
      matricule: '67890 | B | 1',
      brand: 'BMW',
      model: 'X5',
      version: 'xDrive30d M Sport Pack',
      bodyType: 'SUV',
      year: 2022,
      colorExterior: 'Noir Saphir Métallisé',
      colorInterior: 'Cuir Vernasca Cognac',
      fuelType: 'DIESEL',
      transmission: 'AUTOMATIQUE',
      mileage: 45200,
      doors: 5,
      seats: 5,
      fiscalPower: 12,
      location: 'Casablanca Showroom',
      entryDate: daysAgo(22),
      purchasePrice: 520000,
      targetSalePrice: 620000,
      minSalePrice: 590000,
      status: 'RESERVED',
      options: JSON.stringify(['Pack M Sport', 'Suspension pneumatique', 'Laser Light', 'Affichage tête haute', 'Harman Kardon', 'Toit panoramique Sky Lounge']),
      description: 'BMW X5 xDrive30d M Sport Pack complet, véhicule sous garantie constructeur étendue, pneus neufs.',
    },
    {
      code: 'V-2026-0003',
      vin: 'W1N0G8EB3NV200345',
      matricule: '45230 | H | 26',
      brand: 'Mercedes-Benz',
      model: 'GLC',
      version: '220d 4MATIC AMG Line',
      bodyType: 'SUV',
      year: 2022,
      colorExterior: 'Gris Sélénite',
      colorInterior: 'Artico / Dinamica Noir',
      fuelType: 'DIESEL',
      transmission: 'AUTOMATIQUE',
      mileage: 28900,
      doors: 5,
      seats: 5,
      fiscalPower: 9,
      location: 'Rabat Succursale',
      entryDate: daysAgo(18),
      purchasePrice: 410000,
      targetSalePrice: 495000,
      minSalePrice: 470000,
      status: 'IN_STOCK',
      options: JSON.stringify(['Pack AMG Line', 'MBUX Navigation Pro', 'Jantes AMG 20"', 'Pack Stationnement 360', 'Éclairage d’ambiance 64 couleurs']),
      description: 'Mercedes GLC 220d 4MATIC AMG Line, état impeccable, historique vérifié chez Auto Nejma.',
    },
    // 31 - 60 jours
    {
      code: 'V-2026-0004',
      vin: 'WAUZZZF40KA123789',
      matricule: '98765 | D | 7',
      brand: 'Audi',
      model: 'Q7',
      version: '50 TDI quattro S Line 286ch',
      bodyType: 'SUV',
      year: 2021,
      colorExterior: 'Bleu Navarre Métallisé',
      colorInterior: 'Cuir Valcona Noir',
      fuelType: 'DIESEL',
      transmission: 'AUTOMATIQUE',
      mileage: 61300,
      doors: 5,
      seats: 7,
      fiscalPower: 15,
      location: 'Casablanca Showroom',
      entryDate: daysAgo(45),
      purchasePrice: 530000,
      targetSalePrice: 635000,
      minSalePrice: 600000,
      status: 'IN_STOCK',
      options: JSON.stringify(['7 places', 'Finition S Line', 'Audi Virtual Cockpit Plus', 'Matrix LED', 'Bose 3D Sound System', 'Suspension adaptive air']),
      description: 'Audi Q7 50 TDI S Line 7 places, véhicule luxueux et familial très bien configuré.',
    },
    {
      code: 'V-2026-0005',
      vin: 'SALWR2V48LA890123',
      matricule: '34120 | B | 1',
      brand: 'Land Rover',
      model: 'Range Rover Velar',
      version: 'P250 R-Dynamic SE',
      bodyType: 'SUV',
      year: 2020,
      colorExterior: 'Gris Corris',
      colorInterior: 'Cuir Noir Ébène',
      fuelType: 'ESSENCE',
      transmission: 'AUTOMATIQUE',
      mileage: 55000,
      doors: 5,
      seats: 5,
      fiscalPower: 14,
      location: 'Casablanca Showroom',
      entryDate: daysAgo(38),
      purchasePrice: 420000,
      targetSalePrice: 510000,
      minSalePrice: 480000,
      status: 'IN_STOCK',
      options: JSON.stringify(['R-Dynamic Pack', 'Touch Pro Duo', 'Toit panoramique ouvrant', 'Meridian Surround', 'Poignées affleurantes déployables']),
      description: 'Range Rover Velar R-Dynamic très soigné avec entretien suivi chez Smeia.',
    },
    // 61 - 90 jours
    {
      code: 'V-2026-0006',
      vin: 'VF3MCYHZRNL012345',
      matricule: '77881 | E | 1',
      brand: 'Peugeot',
      model: '3008',
      version: '1.5 BlueHDi 130ch GT Line EAT8',
      bodyType: 'SUV',
      year: 2021,
      colorExterior: 'Gris Platinium',
      colorInterior: 'Tissu / Cuir TEP Mistral',
      fuelType: 'DIESEL',
      transmission: 'AUTOMATIQUE',
      mileage: 41900,
      doors: 5,
      seats: 5,
      fiscalPower: 6,
      location: 'Marrakech Showroom',
      entryDate: daysAgo(72),
      purchasePrice: 210000,
      targetSalePrice: 255000,
      minSalePrice: 240000,
      status: 'IN_STOCK',
      options: JSON.stringify(['i-Cockpit 3D', 'Toit ouvrant Black Diamond', 'Caméra de recul', 'Accès bras chargés', 'Phares Full LED']),
      description: 'Peugeot 3008 GT Line, économique et dynamique, historique limpide.',
    },
    // +90 jours (Stock ancien / alerte rotation)
    {
      code: 'V-2026-0007',
      vin: 'UU1HSDJ8654321098',
      matricule: '11225 | A | 7',
      brand: 'Dacia',
      model: 'Duster',
      version: '1.5 dCi 110ch 4x4 Prestige',
      bodyType: 'SUV',
      year: 2020,
      colorExterior: 'Orange Atacama',
      colorInterior: 'Tissu Prestige',
      fuelType: 'DIESEL',
      transmission: 'MANUELLE',
      mileage: 72000,
      doors: 5,
      seats: 5,
      fiscalPower: 6,
      location: 'Tanger Succursale',
      entryDate: daysAgo(105),
      purchasePrice: 135000,
      targetSalePrice: 165000,
      minSalePrice: 155000,
      status: 'IN_STOCK',
      options: JSON.stringify(['Transmission 4x4', 'Media Nav Evolution', 'Caméras multivues', 'Climatisation automatique', 'Jantes alu 17"']),
      description: 'Dacia Duster 4x4 en finition Prestige, idéal pour la montagne et la piste.',
    },
    // Véhicule vendu (pour tests ventes et factures)
    {
      code: 'V-2026-0008',
      vin: 'WBA5R31070FK12345',
      matricule: '88990 | B | 6',
      brand: 'BMW',
      model: 'Série 3',
      version: '320d Pack M 190ch Auto',
      bodyType: 'Berline',
      year: 2021,
      colorExterior: 'Gris Dravit Métallisé',
      colorInterior: 'Cuir Vernasca Noir',
      fuelType: 'DIESEL',
      transmission: 'AUTOMATIQUE',
      mileage: 38400,
      doors: 4,
      seats: 5,
      fiscalPower: 8,
      location: 'Casablanca Showroom',
      entryDate: daysAgo(60),
      purchasePrice: 340000,
      targetSalePrice: 415000,
      actualSalePrice: 410000,
      status: 'SOLD',
      options: JSON.stringify(['Pack M complet', 'BMW Live Cockpit Professional', 'Système Hi-Fi', 'Pack Confort', 'Jantes 19" bicolores']),
      description: 'BMW 320d Pack M vendue avec succès, révisée et livrée.',
    },
  ]

  const createdVehicles: Record<string, Vehicle> = {}
  for (const v of vehiclesData) {
    const vehicle = await prisma.vehicle.upsert({
      where: { vin: v.vin },
      update: v,
      create: v,
    })
    createdVehicles[v.code] = vehicle
  }

  // 7b. Photos Haute Définition pour chaque véhicule du Parc
  const vehiclePhotoMappings: Record<string, string> = {
    'V-2026-0001': '/vehicles/toyota-land-cruiser-2023.jpg',
    'V-2026-0002': '/vehicles/bmw-x5.jpg',
    'V-2026-0003': '/vehicles/mercedes-glc.jpg',
    'V-2026-0004': '/vehicles/audi-q7.jpg',
    'V-2026-0005': '/vehicles/range-rover-velar.jpg',
    'V-2026-0006': '/vehicles/peugeot-3008.jpg',
    'V-2026-0007': '/vehicles/dacia-duster.jpg',
    'V-2026-0008': '/vehicles/bmw-serie-3.jpg',
  }

  for (const [vCode, photoUrl] of Object.entries(vehiclePhotoMappings)) {
    const veh = createdVehicles[vCode]
    if (veh) {
      await prisma.vehiclePhoto.deleteMany({ where: { vehicleId: veh.id } })
      await prisma.vehiclePhoto.create({
        data: {
          vehicleId: veh.id,
          url: photoUrl,
          isPrimary: true,
          category: 'EXTERIEUR',
          order: 0,
        },
      })
    }
  }

  // 8. Dépenses Véhicules (Plusieurs frais par véhicule)
  const prepCategory = await prisma.expenseCategory.findUnique({ where: { code: 'PREP' } })
  const transpCategory = await prisma.expenseCategory.findUnique({ where: { code: 'TRANSP' } })
  const mecaCategory = await prisma.expenseCategory.findUnique({ where: { code: 'MECA' } })
  const adminCategory = await prisma.expenseCategory.findUnique({ where: { code: 'ADMIN' } })
  const pubCategory = await prisma.expenseCategory.findUnique({ where: { code: 'PUB' } })

  const expensesData = [
    {
      code: 'DEP-2026-0001',
      categoryId: prepCategory?.id || '',
      vehicleId: createdVehicles['V-2026-0001'].id,
      label: 'Préparation esthétique et traitement céramique carrosserie',
      amountHT: 3500,
      taxRate: 20.0,
      taxAmount: 700,
      amountTTC: 4200,
      supplierName: 'Auto Clean Pro Detailing',
      paymentMethod: 'CARTE',
      paidBy: 'Adem Maalal',
      status: 'PAID',
    },
    {
      code: 'DEP-2026-0002',
      categoryId: transpCategory?.id || '',
      vehicleId: createdVehicles['V-2026-0001'].id,
      label: 'Rapatriement dépanneuse Tanger -> Casablanca',
      amountHT: 1500,
      taxRate: 20.0,
      taxAmount: 300,
      amountTTC: 1800,
      supplierName: 'Dépannage Express Maroc',
      paymentMethod: 'VIREMENT',
      paidBy: 'Adem Maalal',
      status: 'PAID',
    },
    {
      code: 'DEP-2026-0003',
      categoryId: mecaCategory?.id || '',
      vehicleId: createdVehicles['V-2026-0002'].id,
      label: 'Vidange moteur complète + remplacement plaquettes de frein avant',
      amountHT: 2800,
      taxRate: 20.0,
      taxAmount: 560,
      amountTTC: 3360,
      supplierName: 'Bosch Automotive Maroc',
      paymentMethod: 'VIREMENT',
      paidBy: 'Karim Lahbili',
      status: 'PAID',
    },
    {
      code: 'DEP-2026-0004',
      categoryId: adminCategory?.id || '',
      vehicleId: createdVehicles['V-2026-0002'].id,
      label: 'Droits de mutation et légalisation dossier préfecture',
      amountHT: 850,
      taxRate: 0.0,
      taxAmount: 0,
      amountTTC: 850,
      supplierName: 'Service Administratif Casablanca',
      paymentMethod: 'ESPECES',
      paidBy: 'Nadia Zahra',
      status: 'PAID',
    },
    {
      code: 'DEP-2026-0005',
      categoryId: pubCategory?.id || '',
      vehicleId: createdVehicles['V-2026-0003'].id,
      label: 'Shooting photo professionnel et mise en avant portails Avito / Moteur.ma',
      amountHT: 1200,
      taxRate: 20.0,
      taxAmount: 240,
      amountTTC: 1440,
      supplierName: 'Studio Média Auto',
      paymentMethod: 'CARTE',
      paidBy: 'Sarah Martin',
      status: 'PAID',
    },
  ]

  for (const exp of expensesData) {
    if (exp.categoryId) {
      await prisma.expense.upsert({
        where: { code: exp.code },
        update: exp,
        create: exp,
      })
    }
  }

  // 9. Achats (Purchases)
  await prisma.purchase.upsert({
    where: { code: 'ACH-2026-0001' },
    update: {},
    create: {
      code: 'ACH-2026-0001',
      vehicleId: createdVehicles['V-2026-0001'].id,
      sellerContactId: createdContacts['VEN-001'].id,
      commissionerId: createdContacts['COM-001'].id,
      handledById: adminUser.id,
      purchasePrice: 650000,
      commissionAmount: 5000,
      paymentMethod: 'VIREMENT',
      status: 'CONFIRMED',
      invoiceNumber: 'FAC-FOUR-9823',
      notes: 'Véhicule acheté en parfait état à Monsieur Said El Alami.',
    },
  })

  // 10. Réservations
  await prisma.reservation.upsert({
    where: { code: 'RES-2026-0001' },
    update: {},
    create: {
      code: 'RES-2026-0001',
      vehicleId: createdVehicles['V-2026-0002'].id,
      contactId: createdContacts['CLT-002'].id,
      depositAmount: 25000,
      paymentMethod: 'VIREMENT',
      startDate: daysAgo(3),
      expiryDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
      salespersonName: 'Yassine Benali',
      status: 'ACTIVE',
      notes: 'Acompte de 25 000 DH reçu pour le BMW X5. Client en attente de déblocage crédit Wafasalaf.',
    },
  })

  // 11. Ventes (Sales) avec calculs financiers réalistes
  const sale1 = await prisma.sale.upsert({
    where: { code: 'VEN-2026-0001' },
    update: {},
    create: {
      code: 'VEN-2026-0001',
      saleDate: daysAgo(5),
      vehicleId: createdVehicles['V-2026-0008'].id,
      buyerContactId: createdContacts['CLT-001'].id,
      commissionerId: createdContacts['COM-001'].id,
      salespersonId: yassineUser.id,
      salePrice: 410000, // MAD
      taxRate: 20.0,
      commissionAmount: 4000,
      discountAmount: 5000,
      additionalFees: 1500,
      status: 'CONFIRMED',
      paymentMethod: 'VIREMENT',
      expectedDeliveryDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
      notes: 'Vente confirmée de la BMW Série 3 pour Madame Imane Zahiri.',
    },
  })

  // 12. Paiements (Multi-payments & Soldes)
  await prisma.payment.upsert({
    where: { code: 'ENC-2026-0001' },
    update: {},
    create: {
      code: 'ENC-2026-0001',
      type: 'INFLOW',
      amount: 200000,
      paymentMethod: 'VIREMENT',
      referenceNumber: 'VIR-BP-892345',
      status: 'PAID',
      receivedBy: 'Karim Lahbili',
      contactId: createdContacts['CLT-001'].id,
      saleId: sale1.id,
      notes: 'Premier acompte de 200 000 DH reçu sur le compte Banque Populaire.',
    },
  })

  await prisma.payment.upsert({
    where: { code: 'ENC-2026-0002' },
    update: {},
    create: {
      code: 'ENC-2026-0002',
      type: 'INFLOW',
      amount: 185100,
      paymentMethod: 'VIREMENT',
      referenceNumber: 'VIR-BP-901123',
      status: 'PAID',
      receivedBy: 'Karim Lahbili',
      contactId: createdContacts['CLT-001'].id,
      saleId: sale1.id,
      notes: 'Deuxième versement de 185 100 DH. Reste solde dû : 24 900 DH.',
    },
  })

  // 13. Factures (Invoices)
  const invoice1 = await prisma.invoice.upsert({
    where: { code: 'FAC-2026-0001' },
    update: {},
    create: {
      code: 'FAC-2026-0001',
      type: 'VENTE',
      issueDate: daysAgo(5),
      dueDate: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000),
      contactId: createdContacts['CLT-001'].id,
      saleId: sale1.id,
      subtotalHT: 341666.67,
      taxRate: 20.0,
      taxAmount: 68333.33,
      totalTTC: 410000,
      paidAmount: 385100,
      balanceDue: 24900,
      status: 'PARTIAL',
      paymentMethod: 'VIREMENT',
      terms: 'Paiement du solde restant de 24 900 DH à la livraison du véhicule.',
      notes: 'Facture de vente BMW Série 3 320d Pack M 2021.',
    },
  })

  await prisma.invoiceLine.create({
    data: {
      invoiceId: invoice1.id,
      description: 'BMW Série 3 320d Pack M 190ch Auto (VIN: WBA5R31070FK12345)',
      quantity: 1,
      unitPriceHT: 341666.67,
      taxRate: 20.0,
      totalHT: 341666.67,
      totalTTC: 410000,
    },
  })

  // 14. Régularisations
  await prisma.regularization.upsert({
    where: { code: 'REG-2026-0001' },
    update: {},
    create: {
      code: 'REG-2026-0001',
      type: 'REMISE_COMMERCIALE',
      reason: 'Ajustement suite à révision du prix de vente et geste commercial accessoire',
      targetAmount: 415000,
      adjustedAmount: 410000,
      difference: 5000,
      status: 'VALIDATED',
      contactId: createdContacts['CLT-001'].id,
      saleId: sale1.id,
      invoiceId: invoice1.id,
      handledById: adminUser.id,
      reconciliationData: JSON.stringify({
        saleCode: 'VEN-2026-0001',
        initialTarget: 415000,
        discountApplied: 5000,
        finalTotal: 410000,
      }),
      notes: 'Remise commerciale validée par la direction générale.',
    },
  })

  // 15. Documents (Cartes grises, CIN, Contrats, Factures)
  const documentsData = [
    {
      code: 'DOC-2026-0001',
      title: 'Carte Grise - Toyota Land Cruiser 2023',
      category: 'Administratif',
      type: 'Carte Grise',
      fileUrl: '/storage/documents/cg_land_cruiser_2023.pdf',
      fileSize: 245000,
      mimeType: 'application/pdf',
      vehicleId: createdVehicles['V-2026-0001'].id,
      status: 'VALID',
    },
    {
      code: 'DOC-2026-0002',
      title: 'Attestation d’Assurance Tous Risques - Land Cruiser',
      category: 'Assurance',
      type: 'Attestation Assurance',
      fileUrl: '/storage/documents/assurance_land_cruiser.pdf',
      fileSize: 312000,
      mimeType: 'application/pdf',
      vehicleId: createdVehicles['V-2026-0001'].id,
      expiryDate: new Date(now.getTime() + 180 * 24 * 60 * 60 * 1000),
      status: 'VALID',
    },
    {
      code: 'DOC-2026-0003',
      title: 'Contrôle Technique - Peugeot 3008',
      category: 'Technique',
      type: 'Contrôle Technique',
      fileUrl: '/storage/documents/ct_3008.pdf',
      fileSize: 216000,
      mimeType: 'application/pdf',
      vehicleId: createdVehicles['V-2026-0006'].id,
      expiryDate: new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000),
      status: 'EXPIRING_SOON',
    },
    {
      code: 'DOC-2026-0004',
      title: 'Pièce d’identité CIN - Imane Zahiri',
      category: 'Identite',
      type: 'CIN',
      fileUrl: '/storage/documents/cin_imane_zahiri.pdf',
      fileSize: 128000,
      mimeType: 'application/pdf',
      contactId: createdContacts['CLT-001'].id,
      status: 'VALID',
    },
  ]

  for (const doc of documentsData) {
    await prisma.document.upsert({
      where: { code: doc.code },
      update: doc,
      create: doc,
    })
  }

  // 16. Contrats
  await prisma.contract.upsert({
    where: { code: 'CTR-2026-0001' },
    update: {},
    create: {
      code: 'CTR-2026-0001',
      title: 'Contrat de maintenance et fourniture flotte - AutoFleet Services',
      type: 'Maintenance flotte',
      startDate: daysAgo(30),
      endDate: new Date(now.getTime() + 335 * 24 * 60 * 60 * 1000),
      amountHT: 125000,
      status: 'ACTIVE',
      signatureStatus: 'SIGNED',
      signedAt: daysAgo(29),
      partyContactId: createdContacts['CLT-005'].id,
      terms: 'Prestations d’entretien mensuel préventif et prioritaire sur le parc de véhicules.',
    },
  })

  // 17. Évaluations / Inspections Véhicule
  await prisma.vehicleInspection.upsert({
    where: { code: 'INSP-2026-0001' },
    update: {},
    create: {
      code: 'INSP-2026-0001',
      vehicleId: createdVehicles['V-2026-0001'].id,
      inspectorId: yassineUser.id,
      inspectionDate: daysAgo(10),
      overallScore: 92,
      bodyScore: 95,
      mechanicScore: 98,
      interiorScore: 94,
      electroScore: 90,
      docScore: 100,
      status: 'VALIDATED',
      observations: 'Véhicule en condition d’origine irréprochable. Aucun impact de tôlerie.',
    },
  })

  // 18. Livraisons & Remises
  await prisma.delivery.upsert({
    where: { code: 'LDV-2026-0001' },
    update: {},
    create: {
      code: 'LDV-2026-0001',
      saleId: sale1.id,
      scheduledDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
      status: 'SCHEDULED',
      checklistData: JSON.stringify({
        nettoyageComplet: true,
        doubleDesCles: true,
        pressionPneus: true,
        carnetEntretien: true,
        explicationsFonctionnalites: true,
        giletEtTriangle: true,
      }),
      notes: 'Livraison prévue au Showroom Casablanca en présence du commercial Yassine Benali.',
    },
  })

  // 19. Atelier & Entretien (Work Orders)
  await prisma.workshopOrder.upsert({
    where: { code: 'OT-2026-0001' },
    update: {},
    create: {
      code: 'OT-2026-0001',
      vehicleId: createdVehicles['V-2026-0003'].id,
      clientId: createdContacts['CLT-001'].id,
      technicianId: karimUser.id,
      serviceType: 'Entretien périodique & Contrôle complet',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      scheduledDate: daysAgo(1),
      partsCostHT: 1450,
      laborCostHT: 800,
      taxRate: 20.0,
      totalTTC: 2700,
      notes: 'Remplacement filtres à huile, air et habitacle + contrôle plaquettes.',
    },
  })

  // 20. Agenda & Rendez-vous
  await prisma.appointment.upsert({
    where: { id: 'apt-001' },
    update: {},
    create: {
      id: 'apt-001',
      title: 'Essai sur route Toyota Land Cruiser',
      serviceType: 'Essai véhicule',
      startTime: new Date(now.getTime() + 3 * 60 * 60 * 1000),
      endTime: new Date(now.getTime() + 4 * 60 * 60 * 1000),
      status: 'CONFIRMED',
      workshopBay: 'Atelier 1 - Mécanique',
      clientId: createdContacts['CLT-002'].id,
      advisorId: yassineUser.id,
      notes: 'Essai sur autoroute Casablanca - Rabat demandé par le client.',
    },
  })

  // 21. Marketing Campaigns & Leads (Matching Reference UI/UX #08)
  const campaignsData = [
    {
      id: 'camp-001',
      name: 'Promo Printemps 2025',
      channel: 'Google Ads',
      budgetMAD: 20000,
      spentMAD: 14500,
      leadsCount: 68,
      roiPercent: 412,
      status: 'ACTIVE',
      startDate: daysAgo(45),
    },
    {
      id: 'camp-002',
      name: 'SUV Weekend',
      channel: 'Facebook Ads',
      budgetMAD: 15000,
      spentMAD: 12100,
      leadsCount: 54,
      roiPercent: 365,
      status: 'ACTIVE',
      startDate: daysAgo(30),
    },
    {
      id: 'camp-003',
      name: 'Remarketing Mai',
      channel: 'Google Ads',
      budgetMAD: 10000,
      spentMAD: 8200,
      leadsCount: 38,
      roiPercent: 392,
      status: 'ACTIVE',
      startDate: daysAgo(20),
    },
    {
      id: 'camp-004',
      name: 'Instagram Stories',
      channel: 'Instagram',
      budgetMAD: 8000,
      spentMAD: 6450,
      leadsCount: 27,
      roiPercent: 301,
      status: 'ACTIVE',
      startDate: daysAgo(15),
    },
    {
      id: 'camp-005',
      name: 'Offre Pro Spéciale',
      channel: 'Email Marketing',
      budgetMAD: 5000,
      spentMAD: 3100,
      leadsCount: 19,
      roiPercent: 512,
      status: 'ACTIVE',
      startDate: daysAgo(10),
    },
    {
      id: 'camp-006',
      name: 'Salon Auto 2025',
      channel: 'Événement',
      budgetMAD: 30000,
      spentMAD: 29500,
      leadsCount: 112,
      roiPercent: 278,
      status: 'ENDED',
      startDate: daysAgo(60),
      endDate: daysAgo(5),
    },
    {
      id: 'camp-007',
      name: 'Essai Gratuit Mai',
      channel: 'Google Ads',
      budgetMAD: 10000,
      spentMAD: 2100,
      leadsCount: 9,
      roiPercent: 0,
      status: 'PAUSED',
      startDate: daysAgo(12),
    },
    {
      id: 'camp-008',
      name: 'Parrainage Clients',
      channel: 'Parrainage',
      budgetMAD: 6500,
      spentMAD: 3200,
      leadsCount: 34,
      roiPercent: 642,
      status: 'ACTIVE',
      startDate: daysAgo(40),
    },
  ]

  const createdCampaigns: Record<string, MarketingCampaign> = {}
  for (const c of campaignsData) {
    const camp = await prisma.marketingCampaign.upsert({
      where: { id: c.id },
      update: c,
      create: c,
    })
    createdCampaigns[c.id] = camp
  }

  // Leads matching Reference 08
  const leadsData = [
    {
      code: 'LEAD-2026-0001',
      firstName: 'Sofiane',
      lastName: 'Benali',
      email: 'sofiane.benali@gmail.com',
      phone: '06 12 34 56 78',
      source: 'Site web',
      interestType: 'Achat d’un véhicule SUV',
      estimatedBudget: 189000,
      status: 'NEW',
      campaignId: createdCampaigns['camp-001'].id,
      assignedToId: yassineUser.id,
      tags: JSON.stringify(['SUV', 'Noir', 'Diesel']),
      notes: 'Client très réactif, souhaite programmer un essai ce samedi.',
    },
    {
      code: 'LEAD-2026-0002',
      firstName: 'Karim',
      lastName: 'Haddad',
      email: 'karim.haddad@outlook.fr',
      phone: '07 23 45 67 89',
      source: 'Facebook Ads',
      interestType: 'Achat berline hybride',
      estimatedBudget: 225000,
      status: 'CONTACTED',
      campaignId: createdCampaigns['camp-002'].id,
      assignedToId: salmaUser?.id || yassineUser.id,
      tags: JSON.stringify(['Berline', 'Automatique']),
      notes: 'Premier appel effectué, intéressé par la reprise de son ancien véhicule.',
    },
    {
      code: 'LEAD-2026-0003',
      firstName: 'Nadia',
      lastName: 'El Amrani',
      email: 'nadia.elamrani@gmail.com',
      phone: '06 34 56 78 90',
      source: 'Google Ads',
      interestType: 'Achat SUV Familial 7 places',
      estimatedBudget: 249000,
      status: 'QUALIFIED',
      campaignId: createdCampaigns['camp-001'].id,
      assignedToId: yassineUser.id,
      tags: JSON.stringify(['SUV', '7 places', 'Diesel']),
      notes: 'Financement pré-validé, offre commerciale transmise par email.',
    },
    {
      code: 'LEAD-2026-0004',
      firstName: 'Mehdi',
      lastName: 'Tazi',
      email: 'mehdi.tazi@hotmail.fr',
      phone: '07 45 67 89 01',
      source: 'Instagram',
      interestType: 'Coupé Sport Essence Pack M',
      estimatedBudget: 310000,
      status: 'PROPOSAL',
      campaignId: createdCampaigns['camp-004'].id,
      assignedToId: salmaUser?.id || yassineUser.id,
      tags: JSON.stringify(['Sport', 'Pack M', 'Essence']),
      notes: 'Proposition de prix envoyée, relance prévue demain.',
    },
    {
      code: 'LEAD-2026-0005',
      firstName: 'Omar',
      lastName: 'Lazrak',
      email: 'omar.lazrak@gmail.com',
      phone: '06 56 78 90 12',
      source: 'Site web',
      interestType: 'Véhicule utilitaire ou pick-up 4x4',
      estimatedBudget: 267000,
      status: 'NEGOTIATION',
      campaignId: createdCampaigns['camp-003'].id,
      assignedToId: yassineUser.id,
      tags: JSON.stringify(['4x4', 'Professionnel']),
      notes: 'Négociation remise flotte société.',
    },
    {
      code: 'LEAD-2026-0006',
      firstName: 'Youssef',
      lastName: 'Amine',
      email: 'youssef.amine@yahoo.fr',
      phone: '07 67 89 01 23',
      source: 'Parrainage',
      interestType: 'Berline premium haut de gamme',
      estimatedBudget: 278000,
      status: 'CONVERTED',
      campaignId: createdCampaigns['camp-008'].id,
      assignedToId: salmaUser?.id || yassineUser.id,
      tags: JSON.stringify(['Premium', 'Comptant']),
      notes: 'Vente conclue avec succès et livraison programmée.',
    },
    {
      code: 'LEAD-2026-0007',
      firstName: 'Yanis',
      lastName: 'Bennani',
      email: 'yanis.bennani@gmail.com',
      phone: '06 98 76 54 32',
      source: 'Google Ads',
      interestType: 'SUV Boîte Automatique',
      estimatedBudget: 240000,
      status: 'NEW',
      campaignId: createdCampaigns['camp-001'].id,
      assignedToId: yassineUser.id,
      tags: JSON.stringify(['SUV', 'Diesel', 'Automatique']),
      notes: 'Je suis intéressé par un SUV automatique, budget 240 000 DH. Disponible en semaine après 18h.',
    },
  ]

  for (const l of leadsData) {
    await prisma.lead.upsert({
      where: { code: l.code },
      update: l,
      create: l,
    })
  }

  // 22. Financement / Crédit
  await prisma.financingApplication.upsert({
    where: { code: 'FIN-2026-0001' },
    update: {},
    create: {
      code: 'FIN-2026-0001',
      partnerName: 'Wafasalaf',
      requestedAmount: 350000,
      downPayment: 100000,
      durationMonths: 60,
      monthlyPayment: 4850,
      interestRate: 5.75,
      status: 'IN_ANALYSIS',
      advisorName: 'Adel M.',
      clientId: createdContacts['CLT-002'].id,
      notes: 'Dossier complet transmis avec bulletins de paie et relevés bancaires 3 derniers mois.',
    },
  })

  // 23. Garanties & Assurances
  await prisma.warranty.upsert({
    where: { code: 'GAR-2026-0001' },
    update: {},
    create: {
      code: 'GAR-2026-0001',
      vehicleId: createdVehicles['V-2026-0001'].id,
      clientId: createdContacts['CLT-001'].id,
      warrantyType: 'Garantie Constructeur',
      supplierName: 'Toyota Maroc',
      startDate: daysAgo(60),
      endDate: new Date(now.getTime() + 700 * 24 * 60 * 60 * 1000),
      ceilingAmount: 50000,
      deductible: 500,
      coverageItems: JSON.stringify(['Moteur', 'Boîte de vitesses', 'Électronique', 'Transmission', 'Climatisation']),
      status: 'ACTIVE',
    },
  })

  await prisma.insurancePolicy.upsert({
    where: { code: 'ASS-2026-0001' },
    update: {},
    create: {
      code: 'ASS-2026-0001',
      insurerName: 'AXA Assurance Maroc',
      policyType: 'Tous risques',
      vehicleId: createdVehicles['V-2026-0001'].id,
      clientId: createdContacts['CLT-001'].id,
      annualPremium: 14500,
      startDate: daysAgo(30),
      expiryDate: new Date(now.getTime() + 335 * 24 * 60 * 60 * 1000),
      status: 'ACTIVE',
    },
  })

  // 24. Immatriculations & Dossiers Admin
  await prisma.registrationDossier.upsert({
    where: { code: 'IMM-2026-0001' },
    update: {},
    create: {
      code: 'IMM-2026-0001',
      vehicleId: createdVehicles['V-2026-0008'].id,
      clientId: createdContacts['CLT-001'].id,
      dossierType: 'Mutation Carte Grise',
      region: 'Casablanca-Settat',
      prefecture: 'Anfa',
      feeAmount: 950,
      status: 'IN_PROGRESS',
      checklistData: JSON.stringify({
        cinAcheteur: true,
        carteGriseOriginale: true,
        quitusFiscal: true,
        visiteTechnique: true,
        mandatSigne: true,
      }),
      notes: 'Dossier déposé à la préfecture d’Anfa le 28/05/2025.',
    },
  })

  // 25. Tâches & Approbations
  await prisma.task.upsert({
    where: { id: 'task-001' },
    update: {},
    create: {
      id: 'task-001',
      title: 'Préparer livraison Toyota Land Cruiser',
      category: 'Livraisons',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
      assignedToId: yassineUser.id,
      checklist: JSON.stringify([
        { text: 'Contrôle pression pneus', done: true },
        { text: 'Nettoyage intérieur & extérieur', done: true },
        { text: 'Plein carburant', done: false },
        { text: 'Documents de bord & facture', done: true },
      ]),
    },
  })

  // 26. Communications
  await prisma.communicationMessage.create({
    data: {
      channel: 'WHATSAPP',
      direction: 'INBOUND',
      subject: 'Demande d’information disponibilité',
      content: 'Bonjour Yassine, est-ce que le Land Cruiser 2023 est toujours disponible pour un essai demain ?',
      status: 'READ',
      recipientId: createdContacts['CLT-001'].id,
      senderName: 'Imane Zahiri',
    },
  })

  // 27. Annonces Portails
  await prisma.vehicleListing.upsert({
    where: { code: 'ANN-2026-0001' },
    update: {},
    create: {
      code: 'ANN-2026-0001',
      title: 'Toyota Land Cruiser 2023 VXR V6 4.0L Essence',
      vehicleId: createdVehicles['V-2026-0001'].id,
      priceMAD: 785000,
      status: 'ACTIVE',
      platformsData: JSON.stringify([
        { platform: 'Avito.ma', status: 'Active', url: 'https://avito.ma/lc2023' },
        { platform: 'Moteur.ma', status: 'Active', url: 'https://moteur.ma/lc2023' },
        { platform: 'Auto24.ma', status: 'Active', url: 'https://auto24.ma/lc2023' },
      ]),
      viewsCount: 1245,
      leadsCount: 28,
    },
  })

  // 28. Centre d'Aide / Helpdesk & FAQ
  await prisma.helpdeskTicket.upsert({
    where: { code: 'SUP-2026-0001' },
    update: {},
    create: {
      code: 'SUP-2026-0001',
      subject: 'Prise de rendez-vous révision des 10 000 km',
      category: 'Entretien',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      description: 'Demande de créneau atelier pour vidange d’huile et vérification générale.',
      contactId: createdContacts['CLT-001'].id,
      assignedTo: 'Nadia Zahra',
      satisfactionRating: 5,
    },
  })

  await prisma.knowledgeBaseArticle.upsert({
    where: { id: 'faq-001' },
    update: {},
    create: {
      id: 'faq-001',
      title: 'Quels sont les documents requis pour l’achat d’un véhicule au Maroc ?',
      category: 'Commandes & Achat',
      content: 'Pour finaliser votre achat, vous devez fournir : une copie de votre CIN en cours de validité (ou passeport pour les résidents étrangers), un justificatif de domicile récent et votre attestation de virement bancaire.',
      views: 356,
      helpful: 89,
    },
  })

  // 29. Notifications Système
  const notificationsData = [
    {
      title: 'Stock âgé détecté',
      message: 'Le véhicule Dacia Duster (V-2026-0007) est en stock depuis plus de 90 jours.',
      category: 'Stock',
      severity: 'WARNING',
      link: '/stock/aging',
      isRead: false,
    },
    {
      title: 'Paiement en attente de solde',
      message: 'Facture FAC-2026-0001 : reste dû de 24 900 DH pour Mme Imane Zahiri.',
      category: 'Paiements',
      severity: 'WARNING',
      link: '/invoices',
      isRead: false,
    },
    {
      title: 'Document expirant bientôt',
      message: 'Contrôle technique du Peugeot 3008 expire dans 15 jours.',
      category: 'Documents',
      severity: 'WARNING',
      link: '/documents',
      isRead: false,
    },
    {
      title: 'Réservation active',
      message: 'Réservation RES-2026-0001 pour BMW X5 expire dans 7 jours.',
      category: 'Reservations',
      severity: 'INFO',
      link: '/reservations',
      isRead: true,
    },
  ]

  for (const n of notificationsData) {
    await prisma.notification.create({ data: n })
  }

  // 30. Archive Record de démonstration
  await prisma.archiveRecord.create({
    data: {
      entityType: 'Vehicle',
      entityId: 'arch-veh-001',
      entityCode: 'V-2025-0099',
      summary: 'Toyota Land Cruiser 2021 V6 Essence (Matricule: 12345 | 11 | 2021)',
      archivedReason: 'Vente annulée par désistement client',
      archivedBy: 'Admin Maalal',
      dataSnapshot: JSON.stringify({
        brand: 'Toyota',
        model: 'Land Cruiser',
        year: 2021,
        mileage: 85400,
        color: 'Blanc',
        price: 520000,
      }),
    },
  })

  // 31. Financement & Dossiers Crédit (Reference UI/UX #09)
  const financingData = [
    {
      code: 'FIN-2025-00568',
      partnerName: 'CIM Finance',
      requestedAmount: 325000,
      downPayment: 65000,
      durationMonths: 60,
      monthlyPayment: 5416,
      interestRate: 5.20,
      status: 'IN_ANALYSIS',
      advisorName: 'Adel M.',
      vehicleModelName: 'BMW X3 xDrive20d 2022',
      registrationNumber: '12345 | 72',
      lastStep: 'Analyse crédit',
      notes: 'Client très réactif, dossier transmis à l’organisme de crédit CIM Finance pour validation.',
    },
    {
      code: 'FIN-2025-00567',
      partnerName: 'Wafasalaf',
      requestedAmount: 418000,
      downPayment: 80000,
      durationMonths: 72,
      monthlyPayment: 5805,
      interestRate: 5.75,
      status: 'VERIFICATION',
      advisorName: 'Yassine B.',
      vehicleModelName: 'Mercedes GLC 220d 2021',
      registrationNumber: '67890 | 11',
      lastStep: 'Vérification docs',
      notes: 'Pièces d’identité et relevés bancaires 3 mois en cours de vérification.',
    },
    {
      code: 'FIN-2025-00566',
      partnerName: 'CIM Finance',
      requestedAmount: 249000,
      downPayment: 49000,
      durationMonths: 48,
      monthlyPayment: 4790,
      interestRate: 5.40,
      status: 'APPROVED',
      advisorName: 'Adel M.',
      vehicleModelName: 'Audi A4 2.0 TDI 2020',
      registrationNumber: '34567 | 6',
      lastStep: 'En approbation',
      notes: 'Accord de principe obtenu de la commission de crédit.',
    },
    {
      code: 'FIN-2025-00565',
      partnerName: 'Saham Assurance',
      requestedAmount: 219000,
      downPayment: 39000,
      durationMonths: 48,
      monthlyPayment: 4310,
      interestRate: 5.50,
      status: 'CONTRACT',
      advisorName: 'Sara M.',
      vehicleModelName: 'Peugeot 3008 BlueHDi 2021',
      registrationNumber: '89012 | 26',
      lastStep: 'Contrat à signer',
      notes: 'Contrat d’assurance et crédit prêt pour signature électronique.',
    },
    {
      code: 'FIN-2025-00564',
      partnerName: 'Wafasalaf',
      requestedAmount: 387500,
      downPayment: 77500,
      durationMonths: 60,
      monthlyPayment: 6458,
      interestRate: 5.60,
      status: 'SUBMITTED',
      advisorName: 'Yassine B.',
      vehicleModelName: 'Toyota RAV4 Hybrid 2022',
      registrationNumber: '45678 | 1',
      lastStep: 'Soumis',
      notes: 'Dossier transmis le 30/05/2025 à Wafasalaf Casablanca.',
    },
    {
      code: 'FIN-2025-00569',
      partnerName: 'Eqdom',
      requestedAmount: 339000,
      downPayment: 68000,
      durationMonths: 60,
      monthlyPayment: 5650,
      interestRate: 5.15,
      status: 'DISBURSED',
      advisorName: 'Adel M.',
      vehicleModelName: 'Range Rover Evoque 2022',
      registrationNumber: '90123 | 33',
      lastStep: 'Décaissé',
      notes: 'Fonds décaissés sur le compte bancaire de MAALAL CARS.',
    },
  ]

  for (const f of financingData) {
    await prisma.financingApplication.upsert({
      where: { code: f.code },
      update: f,
      create: f,
    })
  }

  // 32. Atelier & Ordres de Travail (Reference UI/UX #10)
  const workshopOrdersData = [
    {
      code: 'OT-2025-0128',
      serviceType: 'Entretien périodique',
      interventionCategory: 'Entretien',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      scheduledDate: new Date('2025-05-22T09:12:00'),
      dueDate: new Date('2025-05-24T18:00:00'),
      vehicleName: 'BMW Série 3 320d 190 ch',
      licensePlate: 'WW-123-AA',
      mileage: 98450,
      technicianName: 'Yassine Benali',
      workshopBay: 'Poste 2',
      estimatedDuration: '2h30',
      spentDuration: '1h45',
      progressPercent: 68,
      partsCostHT: 118.20,
      laborCostHT: 125.00,
      taxRate: 20.0,
      totalTTC: 328.50,
      notes: 'Contrôle et remplacement des éléments selon le plan d’entretien constructeur.',
      partsList: JSON.stringify([
        { ref: 'HU 816 z', name: 'Filtre à huile', qty: 1, puHT: 12.50, discount: 0, totalHT: 12.50 },
        { ref: 'LX 1987', name: 'Filtre à air', qty: 1, puHT: 18.90, discount: 0, totalHT: 18.90 },
        { ref: '5W30 LL', name: 'Huile moteur 5W30 (5L)', qty: 5, puHT: 14.80, discount: 5, totalHT: 70.30 },
        { ref: 'CUK 2939', name: 'Filtre habitacle', qty: 1, puHT: 16.50, discount: 0, totalHT: 16.50 },
      ]),
    },
    {
      code: 'OT-2025-0127',
      serviceType: 'Diagnostic électronique',
      interventionCategory: 'Électronique',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      scheduledDate: new Date('2025-05-22T10:30:00'),
      dueDate: new Date('2025-05-23T17:00:00'),
      vehicleName: 'Peugeot 308',
      licensePlate: 'AB-456-CD',
      mileage: 64200,
      technicianName: 'Mehdi Kacem',
      workshopBay: 'Poste 1',
      estimatedDuration: '1h30',
      spentDuration: '1h00',
      progressPercent: 50,
      partsCostHT: 45.00,
      laborCostHT: 110.00,
      taxRate: 20.0,
      totalTTC: 186.00,
      notes: 'Voyant moteur allumé. Diagnostic calculateur et effacement défauts.',
    },
    {
      code: 'OT-2025-0126',
      serviceType: 'Remplacement freins AV',
      interventionCategory: 'Mécanique',
      priority: 'HIGH',
      status: 'WAITING_PARTS',
      scheduledDate: new Date('2025-05-21T11:00:00'),
      dueDate: new Date('2025-05-26T18:00:00'),
      vehicleName: 'Renault Clio',
      licensePlate: 'EF-789-GH',
      mileage: 52100,
      technicianName: 'Karim Zahid',
      workshopBay: 'Poste 3',
      estimatedDuration: '2h00',
      spentDuration: '0h45',
      progressPercent: 30,
      partsCostHT: 244.00,
      laborCostHT: 100.00,
      taxRate: 20.0,
      totalTTC: 412.80,
      notes: 'Disques et plaquettes avant ventilés en attente de livraison fournisseur.',
    },
    {
      code: 'OT-2025-0125',
      serviceType: 'Vidange + filtres',
      interventionCategory: 'Entretien',
      priority: 'LOW',
      status: 'PLANNED',
      scheduledDate: new Date('2025-05-21T14:00:00'),
      dueDate: new Date('2025-05-27T12:00:00'),
      vehicleName: 'Audi A4',
      licensePlate: 'IJ-012-KL',
      mileage: 87300,
      technicianName: 'Yassine Benali',
      workshopBay: 'Poste 2',
      estimatedDuration: '1h00',
      spentDuration: '0h00',
      progressPercent: 0,
      partsCostHT: 58.25,
      laborCostHT: 50.00,
      taxRate: 20.0,
      totalTTC: 129.90,
      notes: 'Vidange huile synthétique 5W40 + remplacement filtre à huile et lave-glace.',
    },
    {
      code: 'OT-2025-0124',
      serviceType: 'Distribution + pompe à eau',
      interventionCategory: 'Mécanique',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      scheduledDate: new Date('2025-05-20T08:30:00'),
      dueDate: new Date('2025-05-25T18:00:00'),
      vehicleName: 'Mercedes C220',
      licensePlate: 'MN-345-OP',
      mileage: 124500,
      technicianName: 'Mehdi Kacem',
      workshopBay: 'Poste 4',
      estimatedDuration: '5h00',
      spentDuration: '3h30',
      progressPercent: 75,
      partsCostHT: 729.17,
      laborCostHT: 350.00,
      taxRate: 20.0,
      totalTTC: 1295.00,
      notes: 'Kit courroie de distribution complet + galets + pompe à eau + liquide refroidissement.',
    },
    {
      code: 'OT-2025-0123',
      serviceType: 'Révision complète',
      interventionCategory: 'Entretien',
      priority: 'LOW',
      status: 'COMPLETED',
      scheduledDate: new Date('2025-05-20T10:00:00'),
      dueDate: new Date('2025-05-21T16:00:00'),
      completedDate: new Date('2025-05-21T15:30:00'),
      vehicleName: 'Citroën C3',
      licensePlate: 'QR-678-ST',
      mileage: 41200,
      technicianName: 'Yassine Benali',
      workshopBay: 'Poste 2',
      estimatedDuration: '2h00',
      spentDuration: '2h00',
      progressPercent: 100,
      partsCostHT: 85.00,
      laborCostHT: 80.00,
      taxRate: 20.0,
      totalTTC: 198.00,
      notes: 'Révision des 40 000 km validée et carnet d’entretien tamponné.',
    },
    {
      code: 'OT-2025-0122',
      serviceType: 'Diagnostic moteur',
      interventionCategory: 'Électronique',
      priority: 'MEDIUM',
      status: 'COMPLETED',
      scheduledDate: new Date('2025-05-19T09:00:00'),
      dueDate: new Date('2025-05-20T12:00:00'),
      completedDate: new Date('2025-05-20T11:45:00'),
      vehicleName: 'Ford Focus',
      licensePlate: 'UV-901-WX',
      mileage: 78900,
      technicianName: 'Karim Zahid',
      workshopBay: 'Poste 1',
      estimatedDuration: '1h00',
      spentDuration: '1h00',
      progressPercent: 100,
      partsCostHT: 19.00,
      laborCostHT: 60.00,
      taxRate: 20.0,
      totalTTC: 94.80,
      notes: 'Diagnostic capteur PMH et contrôle faisceau allumage.',
    },
    {
      code: 'OT-2025-0121',
      serviceType: 'Changement embrayage',
      interventionCategory: 'Mécanique',
      priority: 'HIGH',
      status: 'WAITING_PARTS',
      scheduledDate: new Date('2025-05-19T13:30:00'),
      dueDate: new Date('2025-05-28T18:00:00'),
      vehicleName: 'VW Golf',
      licensePlate: 'YZ-234-AB',
      mileage: 112000,
      technicianName: 'Mehdi Kacem',
      workshopBay: 'Poste 4',
      estimatedDuration: '4h30',
      spentDuration: '1h30',
      progressPercent: 35,
      partsCostHT: 418.75,
      laborCostHT: 200.00,
      taxRate: 20.0,
      totalTTC: 742.50,
      notes: 'Kit embrayage bi-masse + butée hydraulique en commande.',
    },
    {
      code: 'OT-2025-0120',
      serviceType: 'Entretien périodique',
      interventionCategory: 'Entretien',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      scheduledDate: new Date('2025-05-18T11:00:00'),
      dueDate: new Date('2025-05-24T17:00:00'),
      vehicleName: 'Nissan Qashqai',
      licensePlate: 'CD-567-EF',
      mileage: 67800,
      technicianName: 'Yassine Benali',
      workshopBay: 'Poste 2',
      estimatedDuration: '2h00',
      spentDuration: '1h15',
      progressPercent: 60,
      partsCostHT: 115.83,
      laborCostHT: 100.00,
      taxRate: 20.0,
      totalTTC: 259.00,
      notes: 'Entretien 60 000 km avec purge liquide de frein.',
    },
    {
      code: 'OT-2025-0119',
      serviceType: 'Freinage AR',
      interventionCategory: 'Mécanique',
      priority: 'LOW',
      status: 'COMPLETED',
      scheduledDate: new Date('2025-05-18T14:30:00'),
      dueDate: new Date('2025-05-19T17:00:00'),
      completedDate: new Date('2025-05-19T16:00:00'),
      vehicleName: 'Opel Astra',
      licensePlate: 'GH-890-IJ',
      mileage: 83400,
      technicianName: 'Karim Zahid',
      workshopBay: 'Poste 3',
      estimatedDuration: '1h30',
      spentDuration: '1h30',
      progressPercent: 100,
      partsCostHT: 96.00,
      laborCostHT: 80.00,
      taxRate: 20.0,
      totalTTC: 211.20,
      notes: 'Remplacement tambours et mâchoires de freins arrière.',
    },
  ]

  for (const ot of workshopOrdersData) {
    await prisma.workshopOrder.upsert({
      where: { code: ot.code },
      update: ot,
      create: ot,
    })
  }

  // 33. Agenda & Rendez-vous (Reference UI/UX #11)
  const appointmentsData = [
    {
      code: 'RDV-2025-0137',
      title: 'Entretien 20 000 km',
      serviceType: 'Entretien 20 000 km',
      startTime: new Date('2025-05-28T09:30:00'),
      endTime: new Date('2025-05-28T11:00:00'),
      status: 'CONFIRMED',
      workshopBay: 'Atelier 1 – Mécanique',
      reminderMin: 15,
      notes: 'Client souhaite contrôle des freins. Vidange + filtres + contrôle général.',
      clientName: 'Sami Martin',
      clientPhone: '06 12 34 56 78',
      clientEmail: 'sami.martin@email.com',
      vehicleName: 'Peugeot 308',
      licensePlate: 'WW-123-AA',
      vin: 'VF3**************',
      mileage: 18450,
      advisorName: 'Adem Maalal',
      source: 'Téléphone',
      duration: '01:30',
      repeat: 'Ne pas répéter',
      history: JSON.stringify([
        { date: '28/05/2025 09:10', title: 'Rendez-vous créé', author: 'Adem Maalal' },
        { date: '28/05/2025 09:15', title: 'Rappel envoyé au client', author: 'Système SMS' },
        { date: '28/05/2025 09:20', title: 'Rendez-vous confirmé', author: 'Sami Martin' },
      ]),
    },
    {
      code: 'RDV-2025-0138',
      title: 'Contrôle technique',
      serviceType: 'Contrôle technique',
      startTime: new Date('2025-05-28T11:00:00'),
      endTime: new Date('2025-05-28T12:00:00'),
      status: 'CONFIRMED',
      workshopBay: 'Atelier 2 – Électricité',
      reminderMin: 15,
      notes: 'Pré-contrôle + passage CT obligatoire.',
      clientName: 'Karim Benali',
      clientPhone: '07 23 45 67 89',
      clientEmail: 'karim.benali@email.com',
      vehicleName: 'Renault Clio',
      licensePlate: 'AB-456-CD',
      vin: 'VF1**************',
      mileage: 42000,
      advisorName: 'Yassine Bejaoui',
      source: 'WhatsApp',
      duration: '01:00',
      repeat: 'Ne pas répéter',
      history: JSON.stringify([
        { date: '28/05/2025 08:30', title: 'Rendez-vous créé', author: 'Yassine Bejaoui' },
        { date: '28/05/2025 08:45', title: 'Rendez-vous confirmé', author: 'Karim Benali' },
      ]),
    },
    {
      code: 'RDV-2025-0139',
      title: 'Révision complète',
      serviceType: 'Révision complète',
      startTime: new Date('2025-05-28T14:00:00'),
      endTime: new Date('2025-05-28T16:00:00'),
      status: 'CONFIRMED',
      workshopBay: 'Atelier 1 – Mécanique',
      reminderMin: 15,
      notes: 'Tous points de contrôle constructeur.',
      clientName: 'Yassine Raoui',
      clientPhone: '06 98 76 54 32',
      clientEmail: 'yassine.raoui@email.com',
      vehicleName: 'BMW Série 3',
      licensePlate: 'EF-789-GH',
      vin: 'WBA**************',
      mileage: 65000,
      advisorName: 'Adem Maalal',
      source: 'Téléphone',
      duration: '02:00',
      repeat: 'Ne pas répéter',
      history: JSON.stringify([
        { date: '27/05/2025 16:00', title: 'Rendez-vous créé', author: 'Adem Maalal' },
        { date: '28/05/2025 09:00', title: 'Rappel envoyé au client', author: 'Système SMS' },
      ]),
    },
    {
      code: 'RDV-2025-0140',
      title: 'Diagnostic électronique',
      serviceType: 'Diagnostic électronique',
      startTime: new Date('2025-05-28T16:30:00'),
      endTime: new Date('2025-05-28T17:30:00'),
      status: 'PENDING',
      workshopBay: 'Atelier 3 – Diagnostic',
      reminderMin: 15,
      notes: 'Lecture défauts + rapport complet injection.',
      clientName: 'Mehdi Larbi',
      clientPhone: '06 11 22 33 44',
      clientEmail: 'mehdi.larbi@email.com',
      vehicleName: 'Audi A3',
      licensePlate: 'IJ-012-KL',
      vin: 'WAU**************',
      mileage: 51200,
      advisorName: 'Mehdi Larbi',
      source: 'Site web',
      duration: '01:00',
      repeat: 'Ne pas répéter',
      history: JSON.stringify([
        { date: '28/05/2025 10:15', title: 'Demande en ligne reçue', author: 'Portail Client' },
      ]),
    },
    {
      code: 'RDV-2025-0141',
      title: 'Vidange + Filtres',
      serviceType: 'Vidange + Filtres',
      startTime: new Date('2025-05-28T18:00:00'),
      endTime: new Date('2025-05-28T18:45:00'),
      status: 'PENDING',
      workshopBay: 'Atelier 2 – Mécanique',
      reminderMin: 15,
      notes: 'Vidange huile moteur + filtre à huile + appoint lave-glace.',
      clientName: 'Nadia Amrani',
      clientPhone: '07 55 66 77 88',
      clientEmail: 'nadia.amrani@email.com',
      vehicleName: 'Volkswagen Golf',
      licensePlate: 'MN-345-OP',
      vin: 'WVW**************',
      mileage: 39000,
      advisorName: 'Yassine Bejaoui',
      source: 'Email',
      duration: '00:45',
      repeat: 'Ne pas répéter',
      history: JSON.stringify([
        { date: '28/05/2025 11:00', title: 'Demande reçue par email', author: 'Yassine Bejaoui' },
      ]),
    },
  ]

  for (const apt of appointmentsData) {
    await prisma.appointment.upsert({
      where: { code: apt.code },
      update: apt,
      create: apt,
    })
  }

  // 34. Régularisations & Rapprochements (Reference UI/UX)
  const regularizationsData = [
    {
      code: 'REG-2025-0050',
      type: 'AJUSTEMENT_PRIX',
      reason: 'Ajustement suite à révision du prix de vente et remise commerciale.',
      vehicleName: 'Toyota Land Cruiser 2023',
      clientName: 'Imane Zahiri',
      saleCode: 'VEN-2025-0032',
      invoiceCode: 'FAC-2025-0038',
      responsibleName: 'Admin Maalal',
      targetAmount: 86500.0,
      adjustedAmount: 83600.0,
      difference: 2900.0,
      status: 'VALIDATED',
      validationDate: new Date('2025-05-30T11:02:00'),
      createdAt: new Date('2025-05-30T10:15:00'),
      reconciliationData: JSON.stringify([
        { item: 'Remise commerciale', amount: 2000.0, type: 'Déduction', initialDiff: 2000.0, finalDiff: 0.0 },
        { item: 'Frais de préparation', amount: 600.0, type: 'Déduction', initialDiff: 600.0, finalDiff: 0.0 },
        { item: 'Accessoires', amount: 300.0, type: 'Addition', initialDiff: 300.0, finalDiff: 0.0 },
      ]),
      auditHistory: JSON.stringify([
        { date: '30/05/2025 11:02', user: 'Admin Maalal', role: 'Administrateur', action: 'Validation', details: 'Régularisation validée et clôturée.' },
        { date: '30/05/2025 10:45', user: 'Nadia K.', role: 'Comptable', action: 'Rapprochement', details: 'Montants affectés et rapprochés.' },
        { date: '30/05/2025 10:20', user: 'Nadia K.', role: 'Comptable', action: 'Passage en attente', details: 'En attente d’affectation des montants.' },
        { date: '30/05/2025 10:15', user: 'Admin Maalal', role: 'Administrateur', action: 'Création', details: 'Régularisation créée.' },
      ]),
    },
    {
      code: 'REG-2025-0049',
      type: 'REMISE_COMMERCIALE',
      reason: 'Remise fidélité client sur véhicule premium.',
      vehicleName: 'BMW X5 xDrive30d',
      clientName: 'Sarah Benali',
      saleCode: 'VEN-2025-0031',
      invoiceCode: 'FAC-2025-0037',
      responsibleName: 'Nadia K.',
      targetAmount: 72000.0,
      adjustedAmount: 70750.0,
      difference: 1250.0,
      status: 'VALIDATED',
      validationDate: new Date('2025-05-29T17:30:00'),
      createdAt: new Date('2025-05-29T16:40:00'),
    },
    {
      code: 'REG-2025-0048',
      type: 'AJUSTEMENT_PRIX',
      reason: 'Correction option jantes alliage et pack cuir.',
      vehicleName: 'Mercedes-Benz GLC 300',
      clientName: 'Youssef El Idrissi',
      saleCode: 'VEN-2025-0030',
      invoiceCode: 'FAC-2025-0035',
      responsibleName: 'Admin Maalal',
      targetAmount: 64500.0,
      adjustedAmount: 62100.0,
      difference: 2400.0,
      status: 'VALIDATED',
      validationDate: new Date('2025-05-29T10:00:00'),
      createdAt: new Date('2025-05-29T09:22:00'),
    },
    {
      code: 'REG-2025-0047',
      type: 'FRAIS_PREPARATION',
      reason: 'Prise en charge frais de covering et céramique.',
      vehicleName: 'Audi Q7 45 TDI',
      clientName: 'Omar Bennis',
      saleCode: 'VEN-2025-0029',
      invoiceCode: 'FAC-2025-0033',
      responsibleName: 'Youssef M.',
      targetAmount: 58000.0,
      adjustedAmount: 56200.0,
      difference: 1800.0,
      status: 'VALIDATED',
      validationDate: new Date('2025-05-28T16:00:00'),
      createdAt: new Date('2025-05-28T15:05:00'),
    },
    {
      code: 'REG-2025-0046',
      type: 'SOLDE_CLIENT',
      reason: 'Ajustement acompte et régularisation TVA.',
      vehicleName: 'BMW X3',
      clientName: 'Laila El Fassi',
      saleCode: 'VEN-2025-0028',
      invoiceCode: 'FAC-2025-0032',
      responsibleName: 'Nadia K.',
      targetAmount: 49500.0,
      adjustedAmount: 48550.0,
      difference: 950.0,
      status: 'RECONCILED',
      createdAt: new Date('2025-05-27T11:33:00'),
    },
    {
      code: 'REG-2025-0045',
      type: 'AJUSTEMENT_PRIX',
      reason: 'Avenant révision prix d’achat reprise.',
      vehicleName: 'Toyota Land Cruiser 2023',
      clientName: 'Mehdi Alaoui',
      saleCode: 'VEN-2025-0027',
      invoiceCode: 'FAC-2025-0031',
      responsibleName: 'Admin Maalal',
      targetAmount: 92000.0,
      adjustedAmount: 88800.0,
      difference: 3200.0,
      status: 'PENDING',
      createdAt: new Date('2025-05-26T14:20:00'),
    },
    {
      code: 'REG-2025-0044',
      type: 'REMISE_COMMERCIALE',
      reason: 'Remise pack hiver négociée.',
      vehicleName: 'Mercedes-Benz GLE 53',
      clientName: 'Karim Tabit',
      saleCode: 'VEN-2025-0026',
      invoiceCode: 'FAC-2025-0029',
      responsibleName: 'Youssef M.',
      targetAmount: 115000.0,
      adjustedAmount: 112900.0,
      difference: 2100.0,
      status: 'PENDING',
      createdAt: new Date('2025-05-26T10:11:00'),
    },
    {
      code: 'REG-2025-0043',
      type: 'FRAIS_PREPARATION',
      reason: 'Régularisation frais immatriculation WW.',
      vehicleName: 'Audi A6',
      clientName: 'Nabil El Hariri',
      saleCode: 'VEN-2025-0025',
      invoiceCode: 'FAC-2025-0028',
      responsibleName: 'Nadia K.',
      targetAmount: 42000.0,
      adjustedAmount: 40550.0,
      difference: 1450.0,
      status: 'RECONCILED',
      createdAt: new Date('2025-05-25T17:45:00'),
    },
    {
      code: 'REG-2025-0042',
      type: 'AJUSTEMENT_PRIX',
      reason: 'Écart de facturation sur accessoires.',
      vehicleName: 'BMW X5 xDrive30d',
      clientName: 'Imane Zahiri',
      saleCode: 'VEN-2025-0024',
      invoiceCode: 'FAC-2025-0026',
      responsibleName: 'Admin Maalal',
      targetAmount: 76000.0,
      adjustedAmount: 74900.0,
      difference: 1100.0,
      status: 'OVERDUE',
      createdAt: new Date('2025-05-24T13:30:00'),
    },
    {
      code: 'REG-2025-0041',
      type: 'AJUSTEMENT_PRIX',
      reason: 'Validation bon de commande et remise accordée.',
      vehicleName: 'Toyota Land Cruiser 2023',
      clientName: 'Ayoub M’rabet',
      saleCode: 'VEN-2025-0023',
      invoiceCode: 'FAC-2025-0025',
      responsibleName: 'Youssef M.',
      targetAmount: 89000.0,
      adjustedAmount: 86250.0,
      difference: 2750.0,
      status: 'VALIDATED',
      validationDate: new Date('2025-05-23T11:00:00'),
      createdAt: new Date('2025-05-23T09:08:00'),
    },
  ]

  for (const reg of regularizationsData) {
    await prisma.regularization.upsert({
      where: { code: reg.code },
      update: reg,
      create: reg,
    })
  }

  // 35. Dépenses (Reference UI/UX #12)
  const categoriesData = [
    { code: 'CAT-TRANSPORT', name: 'Transport' },
    { code: 'CAT-PREPARATION', name: 'Préparation' },
    { code: 'CAT-ATELIER', name: 'Atelier' },
    { code: 'CAT-MARKETING', name: 'Marketing' },
    { code: 'CAT-ADMINISTRATIF', name: 'Administratif' },
    { code: 'CAT-AUTRES', name: 'Autres' },
  ]

  const catMap: Record<string, string> = {}
  for (const cat of categoriesData) {
    const c = await prisma.expenseCategory.upsert({
      where: { code: cat.code },
      update: cat,
      create: cat,
    })
    catMap[cat.name] = c.id
  }

  const ref12ExpensesData = [
    {
      code: 'D-2025-0052',
      label: 'Plein carburant',
      categoryId: catMap['Transport'] || Object.values(catMap)[0],
      supplierName: 'TotalEnergies',
      vehicleName: 'Toyota Land Cruiser',
      amountHT: 70.83,
      taxRate: 20.0,
      taxAmount: 14.17,
      amountTTC: 85.0,
      paymentMethod: 'Carte bancaire',
      status: 'PAID',
      expenseDate: new Date('2025-05-30T14:00:00'),
      mileage: 12650,
      notes: 'Plein de carburant pour Toyota Land Cruiser',
      history: JSON.stringify([
        { date: '30/05/2025 14:00', author: 'Admin Maalal', action: 'Dépense créée' },
        { date: '30/05/2025 14:05', author: 'Admin Maalal', action: 'Paiement par Carte bancaire' },
      ]),
    },
    {
      code: 'D-2025-0051',
      label: 'Préparation esthétique',
      categoryId: catMap['Préparation'] || Object.values(catMap)[0],
      supplierName: 'Auto Clean Pro',
      vehicleName: 'BMW X5',
      amountHT: 375.0,
      taxRate: 20.0,
      taxAmount: 75.0,
      amountTTC: 450.0,
      paymentMethod: 'Carte bancaire',
      status: 'PAID',
      expenseDate: new Date('2025-05-29T14:32:00'),
      mileage: 45230,
      invoiceRef: 'FAC-2025-041',
      notes: 'Nettoyage complet, polissage, cire premium.',
      history: JSON.stringify([
        { date: '29/05/2025 14:32', author: 'Admin Maalal', action: 'Dépense créée par Admin Maalal' },
        { date: '29/05/2025 14:35', author: 'Admin Maalal', action: 'Paiement enregistré (Carte bancaire)' },
        { date: '29/05/2025 14:35', author: 'Admin Maalal', action: 'Statut changé en Payée' },
      ]),
    },
    {
      code: 'D-2025-0050',
      label: 'Révision complète',
      categoryId: catMap['Atelier'] || Object.values(catMap)[0],
      supplierName: 'Garage Premium',
      vehicleName: 'Mercedes GLC',
      amountHT: 650.0,
      taxRate: 20.0,
      taxAmount: 130.0,
      amountTTC: 780.0,
      paymentMethod: 'Virement',
      status: 'PAID',
      expenseDate: new Date('2025-05-28T10:00:00'),
      mileage: 28400,
    },
    {
      code: 'D-2025-0049',
      label: 'Campagne Facebook',
      categoryId: catMap['Marketing'] || Object.values(catMap)[0],
      supplierName: 'Meta Ads',
      vehicleName: '—',
      amountHT: 266.67,
      taxRate: 20.0,
      taxAmount: 53.33,
      amountTTC: 320.0,
      paymentMethod: 'Carte bancaire',
      status: 'PENDING',
      expenseDate: new Date('2025-05-27T16:00:00'),
    },
    {
      code: 'D-2025-0048',
      label: 'Frais bancaires',
      categoryId: catMap['Administratif'] || Object.values(catMap)[0],
      supplierName: 'Banque MAALAL',
      vehicleName: '—',
      amountHT: 37.5,
      taxRate: 20.0,
      taxAmount: 7.5,
      amountTTC: 45.0,
      paymentMethod: 'Prélèvement',
      status: 'PAID',
      expenseDate: new Date('2025-05-26T09:00:00'),
    },
    {
      code: 'D-2025-0047',
      label: 'Assurance',
      categoryId: catMap['Administratif'] || Object.values(catMap)[0],
      supplierName: 'AXA',
      vehicleName: 'Audi Q7',
      amountHT: 516.67,
      taxRate: 20.0,
      taxAmount: 103.33,
      amountTTC: 620.0,
      paymentMethod: 'Prélèvement',
      status: 'PAID',
      expenseDate: new Date('2025-05-25T11:30:00'),
    },
    {
      code: 'D-2025-0046',
      label: 'Pièces de rechange',
      categoryId: catMap['Atelier'] || Object.values(catMap)[0],
      supplierName: 'Auto Parts Plus',
      vehicleName: 'Mercedes GLC',
      amountHT: 216.67,
      taxRate: 20.0,
      taxAmount: 43.33,
      amountTTC: 260.0,
      paymentMethod: 'Carte bancaire',
      status: 'PAID',
      expenseDate: new Date('2025-05-24T15:00:00'),
    },
    {
      code: 'D-2025-0045',
      label: 'Lavage pro & detailing',
      categoryId: catMap['Préparation'] || Object.values(catMap)[0],
      supplierName: 'Clean Car',
      vehicleName: '—',
      amountHT: 100.0,
      taxRate: 20.0,
      taxAmount: 20.0,
      amountTTC: 120.0,
      paymentMethod: 'Espèces',
      status: 'PAID',
      expenseDate: new Date('2025-05-23T12:00:00'),
    },
    {
      code: 'D-2025-0044',
      label: 'Affiches publicitaires',
      categoryId: catMap['Marketing'] || Object.values(catMap)[0],
      supplierName: 'PrintPro',
      vehicleName: '—',
      amountHT: 175.0,
      taxRate: 20.0,
      taxAmount: 35.0,
      amountTTC: 210.0,
      paymentMethod: 'Carte bancaire',
      status: 'PAID',
      expenseDate: new Date('2025-05-22T17:00:00'),
    },
    {
      code: 'D-2025-0043',
      label: 'Abonnement logiciel',
      categoryId: catMap['Administratif'] || Object.values(catMap)[0],
      supplierName: 'Odoo',
      vehicleName: '—',
      amountHT: 20.83,
      taxRate: 20.0,
      taxAmount: 4.17,
      amountTTC: 25.0,
      paymentMethod: 'Carte bancaire',
      status: 'PAID',
      expenseDate: new Date('2025-05-21T08:30:00'),
    },
  ]

  for (const exp of ref12ExpensesData) {
    await prisma.expense.upsert({
      where: { code: exp.code },
      update: exp,
      create: exp,
    })
  }

  // 36. Dépenses Récurrentes (Reference UI/UX #12 Screen 5)
  const recurringData = [
    {
      code: 'R-2025-001',
      title: 'Assurance flotte & showroom',
      category: 'Assurance',
      supplier: 'AXA',
      frequency: 'Mensuelle',
      amountTTC: 620.0,
      status: 'PENDING_VALIDATION',
    },
    {
      code: 'R-2025-002',
      title: 'Abonnement Odoo ERP',
      category: 'Abonnement',
      supplier: 'Odoo',
      frequency: 'Mensuelle',
      amountTTC: 25.0,
      status: 'PENDING_VALIDATION',
    },
    {
      code: 'R-2025-003',
      title: 'Hébergement cloud & serveurs',
      category: 'Hébergement',
      supplier: 'OVH',
      frequency: 'Mensuelle',
      amountTTC: 15.0,
      status: 'PENDING_VALIDATION',
    },
    {
      code: 'R-2025-004',
      title: 'Honoraires comptables',
      category: 'Comptable',
      supplier: 'ExpertCom',
      frequency: 'Mensuelle',
      amountTTC: 150.0,
      status: 'PENDING_VALIDATION',
    },
    {
      code: 'R-2025-005',
      title: 'Location bureaux administratifs',
      category: 'Location bureaux',
      supplier: 'OfficeRent',
      frequency: 'Mensuelle',
      amountTTC: 350.0,
      status: 'PENDING_VALIDATION',
    },
  ]

  for (const rec of recurringData) {
    await prisma.recurringExpense.upsert({
      where: { code: rec.code },
      update: rec,
      create: rec,
    })
  }

  // 37. Factures (Reference UI/UX #13)
  const fallbackContact = await prisma.contact.findFirst()
  if (fallbackContact) {
    const invoicesData = [
      {
        code: 'FAC-2025-0048',
        contactId: fallbackContact.id,
        clientName: 'Imane Zahiri',
        vehicleName: 'Mercedes-Benz GLC',
        saleCode: 'VTE-2025-0034',
        billingAddress: '56, Boulevard Zerktouni, 20150 Casablanca, Maroc',
        clientICE: '112233441066776',
        issueDate: new Date('2025-05-30T10:00:00'),
        dueDate: new Date('2025-06-27T18:00:00'),
        subtotalHT: 72530.0,
        taxRate: 20.0,
        taxAmount: 14506.0,
        totalTTC: 87036.0,
        paidAmount: 87036.0,
        balanceDue: 0.0,
        paymentMethod: 'Virement bancaire',
        status: 'PAID',
        notes: 'Merci pour votre confiance.',
        history: JSON.stringify([
          { date: '30/05/2025, 14:30', author: 'Admin Maalal', action: 'Facture envoyée par email (À : imane.zahiri@email.com)' },
          { date: '30/05/2025, 14:42', author: 'Système', action: 'Email ouvert par le client' },
          { date: '30/05/2025, 14:45', author: 'Imane Zahiri', action: 'Facture téléchargée' },
          { date: '05/06/2025, 09:00', author: 'Système', action: 'Rappel automatique envoyé' },
          { date: '08/06/2025, 11:20', author: 'Admin Maalal', action: 'Paiement reçu (87 036,00 DH par virement bancaire)' },
          { date: '08/06/2025, 11:22', author: 'Système', action: 'Confirmation envoyée' },
        ]),
      },
      {
        code: 'FAC-2025-0047',
        contactId: fallbackContact.id,
        clientName: 'Sarah Benali',
        vehicleName: 'BMW X5',
        saleCode: 'VTE-2025-0033',
        billingAddress: '18 Rue Mohammed V, Casablanca, Maroc',
        clientICE: '223344551099887',
        issueDate: new Date('2025-05-29T11:00:00'),
        dueDate: new Date('2025-06-28T18:00:00'),
        subtotalHT: 13500.0,
        taxRate: 20.0,
        taxAmount: 2700.0,
        totalTTC: 16200.0,
        paidAmount: 16200.0,
        balanceDue: 0.0,
        paymentMethod: 'Espèces',
        status: 'PAID',
      },
      {
        code: 'FAC-2025-0046',
        contactId: fallbackContact.id,
        clientName: 'Youssef El Idrissi',
        vehicleName: 'Audi Q7',
        saleCode: 'VTE-2025-0032',
        billingAddress: '45 Avenue Hassan II, Rabat, Maroc',
        clientICE: '334455661088776',
        issueDate: new Date('2025-05-28T14:00:00'),
        dueDate: new Date('2025-06-27T18:00:00'),
        subtotalHT: 10000.0,
        taxRate: 20.0,
        taxAmount: 2000.0,
        totalTTC: 12000.0,
        paidAmount: 12000.0,
        balanceDue: 0.0,
        paymentMethod: 'Chèque',
        status: 'PAID',
      },
      {
        code: 'FAC-2025-0045',
        contactId: fallbackContact.id,
        clientName: 'Imane Zahiri',
        vehicleName: 'Mercedes-Benz GLC',
        saleCode: 'VTE-2025-0031',
        billingAddress: '56, Boulevard Zerktouni, 20150 Casablanca, Maroc',
        clientICE: '112233441066776',
        issueDate: new Date('2025-05-27T09:30:00'),
        dueDate: new Date('2025-06-26T18:00:00'),
        subtotalHT: 20750.0,
        taxRate: 20.0,
        taxAmount: 4150.0,
        totalTTC: 24900.0,
        paidAmount: 0.0,
        balanceDue: 24900.0,
        paymentMethod: 'Virement',
        status: 'PENDING',
      },
      {
        code: 'FAC-2025-0044',
        contactId: fallbackContact.id,
        clientName: 'Karim Tazii',
        vehicleName: 'BMW X3',
        saleCode: 'VTE-2025-0030',
        billingAddress: '78 Boulevard d\'Anfa, Casablanca, Maroc',
        clientICE: '445566771077665',
        issueDate: new Date('2025-05-27T16:00:00'),
        dueDate: new Date('2025-06-26T18:00:00'),
        subtotalHT: 8166.67,
        taxRate: 20.0,
        taxAmount: 1633.33,
        totalTTC: 9800.0,
        paidAmount: 9800.0,
        balanceDue: 0.0,
        paymentMethod: 'Espèces',
        status: 'PAID',
      },
      {
        code: 'FAC-2025-0043',
        contactId: fallbackContact.id,
        clientName: 'Omar Bennis',
        vehicleName: 'Toyota Land Cruiser',
        saleCode: 'VTE-2025-0029',
        billingAddress: '12 Rue Abou Bakr Seddik, Fès, Maroc',
        clientICE: '556677881066554',
        issueDate: new Date('2025-05-26T10:15:00'),
        dueDate: new Date('2025-06-25T18:00:00'),
        subtotalHT: 26250.0,
        taxRate: 20.0,
        taxAmount: 5250.0,
        totalTTC: 31500.0,
        paidAmount: 0.0,
        balanceDue: 31500.0,
        paymentMethod: 'Virement',
        status: 'PENDING',
      },
      {
        code: 'FAC-2025-0042',
        contactId: fallbackContact.id,
        clientName: 'Laila El Fassi',
        vehicleName: 'Audi A6',
        saleCode: 'VTE-2025-0028',
        billingAddress: '90 Avenue des FAR, Marrakech, Maroc',
        clientICE: '667788991055443',
        issueDate: new Date('2025-05-25T11:45:00'),
        dueDate: new Date('2025-06-24T18:00:00'),
        subtotalHT: 15625.0,
        taxRate: 20.0,
        taxAmount: 3125.0,
        totalTTC: 18750.0,
        paidAmount: 0.0,
        balanceDue: 18750.0,
        paymentMethod: 'Chèque',
        status: 'OVERDUE',
      },
      {
        code: 'FAC-2025-0041',
        contactId: fallbackContact.id,
        clientName: 'Mehdi Alami',
        vehicleName: 'BMW X5',
        saleCode: 'VTE-2025-0027',
        billingAddress: '34 Rue de la Liberté, Tanger, Maroc',
        clientICE: '778899001044332',
        issueDate: new Date('2025-05-24T15:30:00'),
        dueDate: new Date('2025-06-23T18:00:00'),
        subtotalHT: 18583.33,
        taxRate: 20.0,
        taxAmount: 3716.67,
        totalTTC: 22300.0,
        paidAmount: 22300.0,
        balanceDue: 0.0,
        paymentMethod: 'Virement',
        status: 'PAID',
      },
      {
        code: 'FAC-2025-0040',
        contactId: fallbackContact.id,
        clientName: 'Sofia Laabidi',
        vehicleName: 'Mercedes-Benz GLC',
        saleCode: 'VTE-2025-0026',
        billingAddress: '23 Boulevard Franklin Roosevelt, Casablanca, Maroc',
        clientICE: '889900111033221',
        issueDate: new Date('2025-05-23T14:00:00'),
        dueDate: new Date('2025-06-22T18:00:00'),
        subtotalHT: 12833.33,
        taxRate: 20.0,
        taxAmount: 2566.67,
        totalTTC: 15400.0,
        paidAmount: 15400.0,
        balanceDue: 0.0,
        paymentMethod: 'Espèces',
        status: 'PAID',
      },
      {
        code: 'FAC-2025-0039',
        contactId: fallbackContact.id,
        clientName: 'Ayoub M\'rabet',
        vehicleName: 'Toyota Land Cruiser',
        saleCode: 'VTE-2025-0025',
        billingAddress: '67 Avenue Allal Ben Abdellah, Rabat, Maroc',
        clientICE: '990011221022110',
        issueDate: new Date('2025-05-22T09:00:00'),
        dueDate: new Date('2025-06-21T18:00:00'),
        subtotalHT: 24916.67,
        taxRate: 20.0,
        taxAmount: 4983.33,
        totalTTC: 29900.0,
        paidAmount: 0.0,
        balanceDue: 29900.0,
        paymentMethod: 'Virement',
        status: 'PENDING',
      },
    ]

    for (const inv of invoicesData) {
      const createdInv = await prisma.invoice.upsert({
        where: { code: inv.code },
        update: inv,
        create: inv,
      })

      // Add lines for FAC-2025-0048
      if (inv.code === 'FAC-2025-0048') {
        await prisma.invoiceLine.deleteMany({ where: { invoiceId: createdInv.id } })
        await prisma.invoiceLine.createMany({
          data: [
            {
              invoiceId: createdInv.id,
              description: 'Toyota Land Cruiser VX-R',
              quantity: 1,
              unitPriceHT: 72000.0,
              taxRate: 20.0,
              totalHT: 72000.0,
              totalTTC: 86400.0,
            },
            {
              invoiceId: createdInv.id,
              description: 'Préparation esthétique',
              quantity: 1,
              unitPriceHT: 450.0,
              taxRate: 20.0,
              totalHT: 450.0,
              totalTTC: 540.0,
            },
            {
              invoiceId: createdInv.id,
              description: 'Plaque d\'immatriculation',
              quantity: 1,
              unitPriceHT: 80.0,
              taxRate: 20.0,
              totalHT: 80.0,
              totalTTC: 96.0,
            },
          ],
        })
      }
    }
  }

  // ==========================================
  // FEATURE FLAGS (MVP Scope Reduction)
  // ==========================================
  console.log('Seeding feature flags...')
  const featureFlags = [
    // Enabled core MVP features (7)
    { key: 'dashboard', label: 'Tableau de bord', description: 'Tableau de bord principal et KPIs', enabled: true, category: 'core', sortOrder: 1 },
    { key: 'vehicles', label: 'Véhicules', description: 'Catalogue et gestion du parc automobile', enabled: true, category: 'core', sortOrder: 2 },
    { key: 'repairs', label: 'Réparations', description: 'Suivi des réparations et entretien atelier', enabled: true, category: 'services', sortOrder: 3 },
    { key: 'reservations', label: 'Réservations', description: 'Réservations et acomptes clients', enabled: true, category: 'core', sortOrder: 4 },
    { key: 'sales', label: 'Ventes', description: 'Gestion des ventes et commandes', enabled: true, category: 'core', sortOrder: 5 },
    { key: 'documents', label: 'Documents & Photos', description: 'Gestion des photos et documents véhicules', enabled: true, category: 'core', sortOrder: 6 },
    { key: 'settings', label: 'Paramètres', description: 'Configuration générale et administration', enabled: true, category: 'system', sortOrder: 7 },

    // Disabled features (34)
    { key: 'financing', label: 'Financement & Crédit', description: 'Dossiers de financement et simulation crédit', enabled: false, category: 'finance', sortOrder: 10 },
    { key: 'marketing', label: 'Campagnes Marketing', description: 'Gestion des canaux et budgets publicitaires', enabled: false, category: 'marketing', sortOrder: 11 },
    { key: 'workshopAdvanced', label: 'Atelier Avancé & OT', description: 'Ordres de travail, techniciens et ponts atelier', enabled: false, category: 'services', sortOrder: 12 },
    { key: 'reportsAdvanced', label: 'Rapports & Analytique', description: 'Analyses de rentabilité, exports et bilans', enabled: false, category: 'core', sortOrder: 13 },
    { key: 'invoices', label: 'Facturation Complète', description: 'Factures proforma, avoirs et comptabilité', enabled: false, category: 'finance', sortOrder: 14 },
    { key: 'crmAdvanced', label: 'CRM & Pipeline Avancé', description: 'Segmentation, scoring et historique interactions', enabled: false, category: 'crm', sortOrder: 15 },
    { key: 'warranties', label: 'Garanties Véhicules', description: 'Contrats de garantie et réclamations', enabled: false, category: 'services', sortOrder: 16 },
    { key: 'insurance', label: 'Assurances', description: 'Polices d\'assurance et sinistres', enabled: false, category: 'services', sortOrder: 17 },
    { key: 'integrations', label: 'Intégrations & API', description: 'Clés API, webhooks et partenaires externes', enabled: false, category: 'system', sortOrder: 18 },
    { key: 'tasks', label: 'Tâches & Rappels', description: 'Gestion des tâches d\'équipe et rappels', enabled: false, category: 'system', sortOrder: 19 },
    { key: 'communications', label: 'Communications', description: 'Hub de messagerie SMS, Email et WhatsApp', enabled: false, category: 'crm', sortOrder: 20 },
    { key: 'leads', label: 'Prospects & Leads', description: 'Capture et conversion des prospects', enabled: false, category: 'marketing', sortOrder: 21 },
    { key: 'appointments', label: 'Agenda & RDV', description: 'Prise de rendez-vous essai et atelier', enabled: false, category: 'services', sortOrder: 22 },
    { key: 'evaluations', label: 'Évaluations & Reprises', description: 'Inspection technique et cotation de reprise', enabled: false, category: 'core', sortOrder: 23 },
    { key: 'contracts', label: 'Contrats', description: 'Gestion des contrats commerciaux et légaux', enabled: false, category: 'finance', sortOrder: 24 },
    { key: 'registrations', label: 'Immatriculations', description: 'Suivi des cartes grises et immatriculations', enabled: false, category: 'services', sortOrder: 25 },
    { key: 'archives', label: 'Archives', description: 'Registres d\'archivage et historique légal', enabled: false, category: 'system', sortOrder: 26 },
    { key: 'helpdesk', label: 'Support & Tickets', description: 'Gestion des réclamations et tickets support', enabled: false, category: 'services', sortOrder: 27 },
    { key: 'notifications', label: 'Notifications', description: 'Centre de notifications en temps réel', enabled: false, category: 'system', sortOrder: 28 },
    { key: 'sav', label: 'Service Après-Vente', description: 'Planning interventions et réclamations SAV', enabled: false, category: 'services', sortOrder: 29 },
    { key: 'deliveries', label: 'Livraisons & Remises', description: 'Checklist et bons de livraison', enabled: false, category: 'core', sortOrder: 30 },
    { key: 'purchases', label: 'Module Achats', description: 'Gestion détaillée des approvisionnements', enabled: false, category: 'core', sortOrder: 31 },
    { key: 'buyers', label: 'Acheteurs', description: 'Répertoire acheteurs et historique', enabled: false, category: 'crm', sortOrder: 32 },
    { key: 'sellers', label: 'Vendeurs', description: 'Répertoire vendeurs particuliers et pros', enabled: false, category: 'crm', sortOrder: 33 },
    { key: 'commissioners', label: 'Commissionnaires', description: 'Intermédiaires et barèmes commissions', enabled: false, category: 'crm', sortOrder: 34 },
    { key: 'suppliers', label: 'Fournisseurs', description: 'Répertoire fournisseurs pièces et services', enabled: false, category: 'crm', sortOrder: 35 },
    { key: 'clients', label: 'Clients', description: 'Annuaire unifié des clients', enabled: false, category: 'crm', sortOrder: 36 },
    { key: 'finance', label: 'Finance & Trésorerie', description: 'Soldes bancaires et flux financiers', enabled: false, category: 'finance', sortOrder: 37 },
    { key: 'payments', label: 'Module Paiements', description: 'Grand livre des règlements et encaissements', enabled: false, category: 'finance', sortOrder: 38 },
    { key: 'regularizations', label: 'Régularisations', description: 'Ajustements de TVA et régularisations', enabled: false, category: 'finance', sortOrder: 39 },
    { key: 'expenses', label: 'Module Dépenses', description: 'Gestion des notes de frais et dépenses d\'exploitation', enabled: false, category: 'finance', sortOrder: 40 },
    { key: 'balances', label: 'Soldes & Encours', description: 'Encours clients et dettes fournisseurs', enabled: false, category: 'finance', sortOrder: 41 },
    { key: 'stock', label: 'Stock & Rotation', description: 'Analyse fine du vieillissement et rotation du stock', enabled: false, category: 'core', sortOrder: 42 },
    { key: 'listings', label: 'Annonces & Portails', description: 'Diffusion multi-plateforme des annonces', enabled: false, category: 'marketing', sortOrder: 43 },
  ]

  for (const flag of featureFlags) {
    await prisma.featureFlag.upsert({
      where: { key: flag.key },
      update: flag,
      create: flag,
    })
  }

  // 17. Official Parks (Casablanca & Fès)
  const officialParks = [
    {
      code: 'PRK-CAS-01',
      name: 'Park Casablanca Secteur Car',
      city: 'Casablanca',
      address: 'Boulevard Sidi Maârouf, Secteur Car, Casablanca',
      phone: '+212 5 22 78 45 10',
      managerName: 'Adem Maalal',
      capacity: 50,
      isActive: true,
    },
    {
      code: 'PRK-FES-01',
      name: 'Park Fes Maalal Cars Atlas',
      city: 'Fès',
      address: 'Boulevard Allal Ben Abdellah, Quartier Atlas, Fès',
      phone: '+212 5 35 62 78 90',
      managerName: 'Tariq Alami',
      capacity: 35,
      isActive: true,
    },
    {
      code: 'PRK-FES-02',
      name: 'Park Fes Maalal Cars Ennargiss',
      city: 'Fès',
      address: 'Avenue des Forces Armées Royales, Quartier Ennargiss, Fès',
      phone: '+212 5 35 73 15 20',
      managerName: 'Hamza Maalal',
      capacity: 40,
      isActive: true,
    },
  ]

  for (const park of officialParks) {
    await prisma.park.upsert({
      where: { code: park.code },
      update: park,
      create: park,
    })
  }

  console.log('Seed completed successfully! MAALAL CARS is ready.')
}

main()
  .catch((error) => {
    console.error('Seed failed:', error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
